### ISSUE TITLE
Blue-green update doesn't remove nodes from cluster

### ISSUE THREAD

**Issue by ddellarocca** [emqx/emqx-operator#1021]
**Describe the bug**

While testing the blue-green upgrade procedure offered by the operator I've noticed that the EMQX nodes that were part of the ReplicaSet that is being deleted doesn't get removed from the EMQX cluster.

**To Reproduce**
1. Deploy the EMQX Operator
2. Deploy a cluster with the CRD
```yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.4
  coreTemplate:
    spec:
      replicas: 3
  dashboardServiceTemplate:
    enabled : true
  updateStrategy:
    initialDelaySeconds: 10
    type: Recreate
```
3. Update the cluster with the CRD

```yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.5
  coreTemplate:
    spec:
      replicas: 3
  dashboardServiceTemplate:
    enabled : true
  updateStrategy:
    initialDelaySeconds: 10
    type: Recreate
```
4. Watch from the dashboard the nodes still present
![image](https://github.com/emqx/emqx/assets/29358615/a196f5a6-fed4-49a9-adde-867b2e40f220)
![image](https://github.com/emqx/emqx/assets/29358615/4e9a24e6-acbe-45d8-a7a5-1c357aeb634b)

**Expected behavior**
Nodes that are removed should also be removed form EMQX

**Anything else we need to know?**:
Probably this problem occur because the operator tries to reach the old nodes to update the cluster spec, in particular the log lines:
```
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"4bd90d91-2e1e-453b-9284-ff2f42e6c2b6","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"d13a849a-3694-4aa4-a023-958ecffe9a9e","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.3.5:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.3.5:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"4d0cdcbf-9a4d-4cdb-b82e-9eec58d27bdc","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"da13cfe4-3d7f-404b-8c5f-ea95a26c5a2c","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"dc5b1753-45ce-426d-b6e9-5308166fd6be","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"b09d3355-d81b-4dcc-8e19-bac51eb179f1","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:26Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"285ac4ac-3497-475b-b962-db1e704bb816","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:27Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"58ad168f-a609-4519-a24f-c4811101e3f7","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:27Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"23a02e30-430d-4729-84db-9b1d0efd4247","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.1.5:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.1.5:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:29Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"93c1261e-a29f-4495-a3a1-a71b92052852","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.3.5:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.3.5:18083: connect: connection refused" ...
{"level":"error","ts":"2024-03-15T10:00:31Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"600a11e7-25e7-441a-9a3c-bd518882895e","error":"failed to check if sts can be scale down: failed to get node info by API: failed to get API api/v5/nodes: failed to request API: Get \"http://10.244.2.4:18083/api/v5/nodes/emqx@.emqx-headless.emqx.svc.cluster.local\": dial tcp 10.244.2.4:18083: connect: connection refused" ...
```
Are referring to the IPs `10.244.2.4` `10.244.3.5` `10.244.1.5` which are the old nodes that are deleted, the new ones are `10.244.1.6` `10.244.2.5` `10.244.3.6`.

**Environment details:**:
- Kubernetes version: 1.21.14 KinD
- Cloud-provider/provisioner: Local
- emqx-operator version: 2.2.14
- Install method: e.g. helm/static manifests: Helm

**Comment by Rory-Z** [comment]
Hi @ddellarocca the default value of the `cluster.autoclean` is 24h in EMQX config, it's means EMQX will clean the stopped node after 24h, I think that is the reason of the deleted node still in EMQX dashboard.

**Comment by ddellarocca** [comment]
Ok, then but why if I manually scale the ReplicaSet the removed nodes gets instantly removed from the cluster?

**Comment by Rory-Z** [comment]
> Ok, then but why if I manually scale the ReplicaSet the removed nodes gets instantly removed from the cluster?

Because the replicant node of emqx is stateless node, and the core node of emqx is stateful node. please check https://docs.emqx.com/en/enterprise/latest/deploy/cluster/mria-introduction.html#architecture

**Comment by ddellarocca** [comment]
But wait I'm still talking about the Core node, I don't have any replicant nodes.

**Comment by Rory-Z** [comment]
> But wait I'm still talking about the Core node, I don't have any replicant nodes.

You side `if I manually scale the ReplicaSet the removed nodes gets instantly removed from the cluster?`, if you means the Kubernetes resource of `ReplicaSet`, it's EMQX replicant node, the EMQX core node deploy by `StatefulSet`

**Comment by ddellarocca** [comment]
Yes, sorry I mistyped. I meant `StatefulSet` not `ReplicaSet`.

**Comment by Rory-Z** [comment]
Oh, Can I describe your steps? 

1. Deploy only core node cluster by EMQX operator.
2. Target blue-green update, and after it's done, check EMQX dashboard, the old core node list still in EMQX dashboard, and they status is `stopped`
3. Modify the `.spec.coreTemplate.spec.replicas` of the EMQX customer resource, and wait it ready, then the old core node list is hide in EMQX dashboard

May I right?

**Comment by ddellarocca** [comment]
Almost, the first 2 points are correct and related to the blue-green deployment.
What I've tried then is to scale the cluster without changing the version in order to check if it was an Operator problem or an EMQX problem.
To do so I've scaled up the `.spec.coreTemplate.spec.replicas` and then back again, the node started then stopped is not removed from the cluster (same as bluegreen upgrade), doing the same thing but scaling the `StatefulSet` directly the node gets correctly removed from the EMQX cluster as well.


For example:

- Current status: 3 nodes up
![image](https://github.com/emqx/emqx-operator/assets/29358615/d9a1ada8-f47e-43a0-860e-7043f00d6f4b)
![image](https://github.com/emqx/emqx-operator/assets/29358615/49ffc56e-535b-4bac-b7c1-348d96b796f4)

- Change the `.spec.coreTemplate.spec.replicas` from 3 to 4, a new node gets added without creating a new `StatefulSet`
![image](https://github.com/emqx/emqx-operator/assets/29358615/da5b463a-fdf1-44e8-b408-22987c1702c3)
![image](https://github.com/emqx/emqx-operator/assets/29358615/7bfc39d6-714d-4c84-af65-3a47a442933d)

- Revert `.spec.coreTemplate.spec.replicas` to 3, the node gets removed from k8s but not from the cluster 
![image](https://github.com/emqx/emqx-operator/assets/29358615/d94bafc4-a00c-4ff6-bbb7-45350db42737)

If i repeat those step but shutting down the operator first and modify the `.spec.replicas` of the `StatefulSet` by hand the node gets correctly removed from the cluster.
![image](https://github.com/emqx/emqx-operator/assets/29358615/d27b089e-e8b3-4f85-ba7e-04e8fd5a10c9)

**Comment by ddellarocca** [comment]
Wait it popped up again after 5 minute in state stopped, so it is not related to the Operator.

**Comment by Rory-Z** [comment]
Interesting, I think the node list have the stopped state node is correct, but I'm not sure why it until popped up after 5 minutes. I guess this may be related to you closing the EMQX operator, because EMQX operator will check the state of EMQX pod, it will set EMQX pod ready when EMQX application ready, and when you closed EMQX operator, this will be invalid.

**Comment by Rory-Z** [comment]
> Clould be that by default the Operator set EMQX_CLUSTER__DISCOVERY_STRATEGY to dns instead of k8s?

the default value of `EMQX_CLUSTER__DISCOVERY_STRATEGY` is `dns`, you can check it in Pod's env.

**Comment by JimMoen** [comment]
> Clould be that by default the Operator set `EMQX_CLUSTER__DISCOVERY_STRATEGY` to `dns` instead of `k8s`? And `cluster.autoclean` is 5m by default but the nodes are still there as stopped even after more than 5m (ref. https://www.emqx.io/docs/en/latest/deploy/cluster/introduction.html#cluster-node-autoclean).

This document page have not be updated in time.
The default value of `cluster.autoclean` in version v5.5.1 is `24h`。
Plz refer to the [Conifguration Manual](https://www.emqx.io/docs/en/v5.5.1/hocon/#V-cluster-S-cluster-autoclean), which is automatically generated based on the code.

**Comment by ddellarocca** [comment]
Setting the cluster autoclean will infact remove nodes after 5minutes from the ui

```HOCON
      cluster {
        autoclean = "5m"
      }
```
