### ISSUE TITLE
EMQX Operator compatibility problem in K8S

### ISSUE THREAD

**Issue by IBeyondy** [emqx/emqx-operator#1045]
**Describe the bug**
When I use emqx-operator versioned 2.2.21 to install emqx versioned 5.6+ in K8S versioned 1.20, emqx is failed to start.

It says PodDisruptionBudget in "v1" is not existed. 

When I check K8S doc, I found PodDisruptionBudget in "v1" is supported in k8s 1.21+ .

**To Reproduce**
Install emqx-ee versioned 5.6+ in 1.20 k8s cluster.

**Expected behavior**
Use different version of PodDisruptionBudget based on different k8s cluster version.
- (~, 1.20] : policy/v1beta1
- [1.21, ~): policy/v1

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: 1.20
- Cloud-provider/provisioner:
- emqx-operator version: 2.2.21
- Install method: e.g. helm/static manifests

**Comment by Rory-Z** [comment]
Hi @IBeyondy This has been fixed in 2.2.22, please try it.
I don't have K8s cluster of 1.20, so if you have any problem, please let me know
