### ISSUE TITLE
Wait updates to apiVersion v1beta3

### ISSUE THREAD

**Issue by Rory-Z** [emqx/emqx-operator#105]
TODO:

+ Delete `.spec.lables`, should use `meta.labels`
+ Delete `.spec.annotations`, should use `meta.annotations`
+ EmqxEnterprise's `.spec.license` supports base64 encoding, and support external secret
+ Delete `.spec.serviceAccount`, when use emqx 4.4.x, serviceAccount is not required

**Comment by kiragoo** [comment]
The reason for **Delete `.spec.serviceAccount`, when use emqx 4.4.x, serviceAccount is not required** should be explained, or attach the links of the docs related better.
