### ISSUE TITLE
Support ignore_readonly for EMQX configure API

### ISSUE THREAD

**Issue by Rory-Z** [emqx/emqx-operator#1051]
EMQX 5.7.0 supported `ignore_readonly=true` for `/api/v5/configs`, so EMQX operator doesn't need to parse HOCON config

Ref: https://github.com/emqx/emqx/pull/12940

**Comment by zmstone** [comment]
already fixed in 2.2.24 ?

**Comment by Rory-Z** [comment]
> already fixed in 2.2.24 ?

Yes, it's fixed
