### ISSUE TITLE
Allow disabling uptime in status objects

### ISSUE THREAD

**Issue by rouke-broersma** [emqx/emqx-operator#1052]
**Is your feature request related to a problem? Please describe.**
EMQX operator is constantly updating the status object with the current uptime. This is imo unnecessary wear and tear on my hardware. 

**Describe the solution you'd like**
Allow disabling tracking uptime in the status object

**Describe alternatives you've considered**
Record timestamp up_since: <timestamp> instead of uptime in seconds.

**Comment by Rory-Z** [comment]
Can you tell me the specific fields?

**Comment by rouke-broersma** [comment]
- apps.emqx.io/v2beta1/EMQX/status.coreNodes[*].uptime
- apps.emqx.io/v2beta1/EMQX/status.replicantNodes[*].uptime

See: https://docs.emqx.com/en/emqx-operator/latest/reference/v2beta1-reference.html#emqxnode

Apparently it's even the uptime in milliseconds.

**Comment by Rory-Z** [comment]
Sorry for delay, I'll fix this.

**Comment by Rory-Z** [comment]
Maybe just delete `apps.emqx.io/v2beta1/EMQX/status.coreNodes[*].uptime` and `apps.emqx.io/v2beta1/EMQX/status.replicantNodes[*].uptime
` is good ?

**Comment by rouke-broersma** [comment]
If it's not needed/used by the operator I would suggest simply removing it yes.

**Comment by Rory-Z** [comment]
Hi @rouke-broersma EMQX operator 2.2.23 has been released https://github.com/emqx/emqx-operator/releases

**Comment by rouke-broersma** [comment]
Just updated, looks good thanks!
