### ISSUE TITLE
Ability to disable PDB when needed

### ISSUE THREAD

**Issue by mdaguete** [emqx/emqx-operator#1056]
**Is your feature request related to a problem? Please describe.**

We need to shutdown the non production kubernetes clusters and the emqx operator pdb breaks the shutdown.

**Describe the solution you'd like**

A flag to enable the pdb when needed.

**Comment by Rory-Z** [comment]
EMQX operator just create PDB, it will not update it, so maybe you can set `.spec.minAvailable = 0` and then shutdown your K8s ?
