### ISSUE TITLE
k8s 不能正常安装emqx-operator

### ISSUE THREAD

**Issue by Alixxxxxxx** [emqx/emqx-operator#1064]
bug信息如下：

Trace[534228874]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get emqxplugins.apps.emqx.io) 60001ms (16:41:41.083)
Trace[534228874]: [1m0.002031552s] [1m0.002031552s] END
E0724 16:41:41.083818       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1beta4.EmqxPlugin: failed to list *v1beta4.EmqxPlugin: the server was unable to return a response in the time allotted, but may still be processing the request (get emqxplugins.apps.emqx.io)
W0724 16:41:41.083515       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1beta4.EmqxEnterprise: the server was unable to return a response in the time allotted, but may still be processing the request (get emqxenterprises.apps.emqx.io)
I0724 16:41:41.083853       1 trace.go:236] Trace[1711129237]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229 (24-Jul-2024 16:40:41.081) (total time: 60001ms):
Trace[1711129237]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get emqxenterprises.apps.emqx.io) 60001ms (16:41:41.083)
Trace[1711129237]: [1m0.00188664s] [1m0.00188664s] END
E0724 16:41:41.083863       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1beta4.EmqxEnterprise: failed to list *v1beta4.EmqxEnterprise: the server was unable to return a response in the time allotted, but may still be processing the request (get emqxenterprises.apps.emqx.io)

这个是啥原因呀？ 谢谢。

**Comment by Rory-Z** [comment]
Looks it's a network issue, please make sure your Kubernetes has correct config.

And when you create issue, please fill the template, it's very useful to help us to find the problem.
