### ISSUE TITLE
There is no emqx-operator 2.2.24 image

### ISSUE THREAD

**Issue by tjwallace** [emqx/emqx-operator#1075]
See https://github.com/emqx/emqx-operator/pkgs/container/emqx-operator

Version `2.2.24` of the helm chart tries to pull image `emqx-operator:2.2.24` which does not exist.

**Comment by Rory-Z** [comment]
Thanks for the reminder, now `ghcr.io/emqx/emqx-operator:2.2.24` has been pushed
