### ISSUE TITLE
[Feature] Specify secrets for listeners TLS certificates

### ISSUE THREAD

**Issue by mdallaire** [emqx/emqx-operator#110]
**Is your feature request related to a problem? Please describe.**
There does not seem to be a way to use pre-existing certificates in kind: EmqxBroker

**Describe the solution you'd like**
Have an option to define an existing secret containing a TLS certificate for the secure ports

**Describe alternatives you've considered**
I can't find one right now in the information available on the kind: EmqxBroker. An other way of doing this would be to be able to specifiy an existing cluster issuer and dns names for automatic generation of the needed certs.

Related issue https://github.com/emqx/emqx/issues/6337

**Comment by Rory-Z** [comment]
Hi, @mdallaire 
It's a good question and we have plans to make it happen, it's already in our roadmap
