### ISSUE TITLE
emqx-ee cannot be created normally

### ISSUE THREAD

**Issue by p1qt** [emqx/emqx-operator#111]
**Describe the bug**
when i use this yaml create emqx-ee，could not create successfully

~~~yaml
#emqx-ee.yaml
apiVersion: apps.emqx.io/v1beta2
kind: EmqxEnterprise
metadata:
  name: emqx-ee
spec:
  serviceAccountName: "emqx"
  image: emqx/emqx-ee:4.4.0
  replicas: 3
  labels:
    cluster: emqx
  storage:
    storageClassName: hostpath
    resources:
      requests:
        storage: 20Mi
    accessModes:
    - ReadWriteOnce
  env:
    - name: "EMQX_LOG__LEVEL"
      value: "debug"
  emqxTemplate:
    # acl: []
    plugins: 
      - name: emqx_management
        enable: true
      - name: emqx_recon
        enable: true
      - name: emqx_retainer
        enable: true
      - name: emqx_dashboard
        enable: true
      - name: emqx_telemetry
        enable: true
      - name: emqx_rule_engine
        enable: true
      - name: emqx_bridge_mqtt
        enable: false
    # modules: 
    #   
    #   - name: internal_acl
    #     enable: true
    #     configs:
    #       acl_rule_file: etc/acl.conf
    #   - name: presence
    #     enable: true
    #     configs:
    #       qos: 0
    #   - name: recon
    #     enable: true
    #     configs: {}
    #   - name: retainer
    #     enable: true
    #     configs:
    #       expiry_interval: 0
    #       max_payload_size: 1MB
    #       max_retained_messages: 0
    #       storage_type: ram


    listener:
      type: NodePort
      ports:
        mqtt: 1883
        mqtts: 8883
        ws: 8083
        wss: 8084
        dashboard: 18083
        api: 8081

~~~
This is the error screenshot
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/48899661/153829547-0dc1145a-2c39-476e-a245-f41c9b451784.png">

**To Reproduce**
~~~shell
kubeclt apply -f emqx-ee.yaml
~~~

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version:v1.22.4 (docker-desktop)
- emqx-operator version: v1.1.1
- Install method: helm

**Comment by imwbl** [comment]
but when i use broker can successfully created

**Comment by Rory-Z** [comment]
Hi, @p1qt 
Can you provide a log of when the error occurred? You can view the logs using the following command.
```
kubectl logs -f -l "control-plane=controller-manager" -n emqx-operator-system -c manager
```

**Comment by p1qt** [comment]
> Hi, @p1qt Can you provide a log of when the error occurred? You can view the logs using the following command.
> 
> ```
> kubectl logs -f -l "control-plane=controller-manager" -n emqx-operator-system -c manager
> ```

**Thanks, this problem have solved, not a bug😅.**

**Comment by Rory-Z** [comment]
Cool

**Comment by p1qt** [comment]
sorry，just now i use wrong yaml.This is the error screenshot
<img width="809" alt="image" src="https://user-images.githubusercontent.com/48899661/153982613-4d533556-5a57-4032-b84f-ac38ad0b400e.png">

**Comment by Rory-Z** [comment]
Hi, @p1qt 
I need more logs, you can use `--tail` to print more logs, like this:
```
kubectl logs -f -l "control-plane=controller-manager" -n emqx-operator-system -c manager --tail=100
```
