### ISSUE TITLE
[Feature Request] Add support to set annotations on the generated Service

### ISSUE THREAD

**Issue by ammmze** [emqx/emqx-operator#116]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add an annotation to the `Service` that the `EmqxBroker` generates such as: `coredns.io/hostname: "mqtt.example.com"`. This annotation specifically in my case causes coredns to add a DNS record resolving `mqtt.example.com`. to the ip address of the service.

**Describe the solution you'd like**
I think the `spec.emqxTemplate.listener` object on the `EmqxBroker` should support an `annotations` field which would then be used when generating the `Service` around [here](https://github.com/emqx/emqx-operator/blob/32377cd0dba488c965e850284a28f23a84fe34fd/pkg/service/generator.go#L180-L184).

**Describe alternatives you've considered**
Alternatives would require that my load balancer ip is static and then manually adding the DNS record to core dns.
Or manually crafting a custom `Service` to run side by side with the one produced by the operator and effectively just leave the generated `Service` un-used.

**Comment by Rory-Z** [comment]
@ammmze 
Cool ！we will include this in our development plans
