### ISSUE TITLE
Could not load plugin

### ISSUE THREAD

**Issue by Slideee** [emqx/emqx-operator#236]
emqx-operator ：1.2.0
emqx： 4.4.1

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/48793283/173777895-e348ee41-9666-4ef3-9377-63f200ed9da5.png">

**Comment by Rory-Z** [comment]
Please use `EmqxPlugin` custom resource deploy plugins

**Comment by Slideee** [comment]
> Please use `EmqxPlugin` custom resource to deploy plugins, like this: https://github.com/emqx/emqx-operator/blob/main/config/samples/emqx/v1beta3/emqx-plugin.yaml

The execution through the `EmqxPlugin ` is successful, but from the dashboard and emqx_ctl, the plugin is not started.
![image](https://user-images.githubusercontent.com/48793283/173782493-84bda1fb-f210-4de4-96c9-9f1a93fbf14e.png)

![image](https://user-images.githubusercontent.com/48793283/173783877-decb6ba3-0add-4f82-9dfd-9e28cab462db.png)

I tried to load other plugins via /bin/emqx_ctl and it didn't work
![image](https://user-images.githubusercontent.com/48793283/173783761-ad93df81-5300-432d-a74b-0638e9314f4f.png)

**Comment by Rory-Z** [comment]
Looks plugin config failed, please modify ".spec.config" for `EmqxPlugin`:
```
push.gateway.server ---> prometheus.push.gateway.server
interval  ---> prometheus.interval
```

**Comment by Slideee** [comment]
> 
Configure ".spec.config" for EmqxPlugin as you said has been successful.

The reason for the console error "parse_config_file_failed" seems to be that there is no default `.conf`  when the plugin is initialized.Is it necessary to initialize the default `.conf` files for all plugins here?

![image](https://user-images.githubusercontent.com/48793283/173980745-5ee1b4c0-a5ba-4852-ab4f-1e116864b53a.png)

![image](https://user-images.githubusercontent.com/48793283/173980576-2d585182-ca56-4d0e-8017-918442a8e9fb.png)

**Comment by Rory-Z** [comment]
Yes，we don't have default config for plugin.
This's looks like load `emqx_auth_mysql` failed, did you load this plugin? or this is what `EMQX` does?

**Comment by Slideee** [comment]
> Yes，we don't have default config for plugin. This's looks like load `emqx_auth_mysql` failed, did you load this plugin? or this is what `EMQX` does?

I loaded `emqx_auth_mysql` through the dashboard, and then reported an error of 'parse_config_file_failed'. Looking at the log, I found that there was no `emqx_auth_mysql.conf` in the mounted directory. 
So I think it seems that the operator should mount the default configuration of the plugin, otherwise it cannot be manually started and stopped through the dashboard

**Comment by Rory-Z** [comment]
I see，let me add default config for next release
