### ISSUE TITLE
when use helm uninstall the emqx-operator release, the emqxplugins.apps.emqx.io crd is not remove. 

### ISSUE THREAD

**Issue by wonderful-ya** [emqx/emqx-operator#242]
**Describe the bug**
when use helm uninstall the emqx-operator release, the emqxplugins.apps.emqx.io crd is not remove. 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/106941947/174712685-77df59c5-6f6b-4788-b7c7-bee3718bccfc.png">

**To Reproduce**
see the picture above。
**Expected behavior**
all the crds removed, when use helm uninstall the emqx-operator release.

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: 
`
 ~ % kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
`

`
% helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
`
- Cloud-provider/provisioner:minikube
- emqx-operator version: master branch
- Install method: e.g. helm

**Comment by Rory-Z** [comment]
This is a serious mistake, thanks for the feedback
