### ISSUE TITLE
Possibility to define additional containers

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/emqx-operator#252]
**Is your feature request related to a problem? Please describe.**
We are operating emqx broker together with a companion container for cloudsql-proxy.

**Describe the solution you'd like**
Because of this, it would be very useful to be able to specify additional containers in the EmqxBroker crd.

**Describe alternatives you've considered**
Can't think of an alternative atm.

**Comment by Rory-Z** [comment]
Hi, @mariusstaicu Thanks for your feedback, maybe we can add `containers` for `.spec` in emqx custom resources, what do you think?

**Comment by mariusstaicu** [comment]
yes, would be great

**Comment by Rory-Z** [comment]
Cool, we will finish it

**Comment by mariusstaicu** [comment]
amazing, thanks
