### ISSUE TITLE
Reloader sidecar version is hardcoded

### ISSUE THREAD

**Issue by AsyncLegs** [emqx/emqx-operator#266]
Hello there!
Thanks for the great operator software.

I'm trying to deploy this operator and it's not possible to start reload sidecars on raspberry pi nodes as version is hardcoded to emqx-operator-reloader:0.0.1 one - which compiled without arm support.

Is there any way to define this package version somewhere in the operator config?

https://github.com/emqx/emqx-operator/blob/3f2ba1f57839fd3397b20782cda06b4138004782/controllers/apps/emqx_handler.go#L128

**Comment by Rory-Z** [comment]
Hi，@AsyncLegs, Sorry for this, I've just pushed the arm image to docker hub, please try again.

> Is there any way to define this package version somewhere in the operator config?

We have think about this, but we are not sure where it is better to define the reloader image in EMQX Custom Resources, do you have any ideas?

**Comment by AsyncLegs** [comment]
Appreciate your blazing fast reaction on that :) 

Probably it doesn't make any sense to define that image somewhere, it seems like some internal operator sidecar tool anyways.

**Comment by Rory-Z** [comment]
Yes, so we choose hardcode this image in code for now, maybe in the future we will let the user define it, if we need do this.
Anyway, does it work for you now？

**Comment by AsyncLegs** [comment]
Looks like dockerhub hasn't updated tags yet: https://hub.docker.com/r/emqx/emqx-operator-reloader/tags

will try a bit later

**Comment by Rory-Z** [comment]
OK, look forward you good news

**Comment by AsyncLegs** [comment]
Ohh, i was able to find pushed stuff, but looks like typo here: https://hub.docker.com/r/emqx/emqx-operatpr-reloader/tags
@Rory-Z

**Comment by Rory-Z** [comment]
Oh, it's my mistake, I've push image again, and docker hub is ready: https://hub.docker.com/r/emqx/emqx-operator-reloader/tags

**Comment by AsyncLegs** [comment]
Now, it fixed!
Thanks

**Comment by Rory-Z** [comment]
Cooooool
