### ISSUE TITLE
emqxBroker CRD fails to validate via server side dry-run

### ISSUE THREAD

**Issue by ryphon** [emqx/emqx-operator#306]
### What happened?

The EMQX crd has issues with CD systems like FluxCD or ArgoCD that do server-side apply dry-runs to validate changes for reconciliation.

### What did you expect to happen?

All potential fields on the CRD are on the schema so that server side dry-runs succeed with zero changes (or configured to ignore said changes)

### How can we reproduce it (as minimally and precisely as possible)?

Apply a broker crd:
```
kubectl apply --server-side -f broker.yaml
```

then run:

```
kubectl apply --server-side -f broker.yaml --dry-run=server
```

The response is likely to be:
```
Error from server: .spec.emqxTemplate.serviceTemplate.metadata.creationTimestamp: field not declared in schema
```

### Anything else we need to know?

```
Warning  ReconciliationFailed     91s (x3 over 11m)  kustomize-controller  EmqxBroker/mqtt/emqx dry-run failed, error: .spec.emqxTemplate.serviceTemplate.metadata.creationTimestamp: field not declared in schema
``` 
This is the message directly from Flux, but the command in the reproduction steps is all that FluxCD is doing behind the covers.

### EMQX version

<details>

```console
bash-5.1$ emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.4.0
uptime    : 17 minutes, 8 seconds
datetime  : 2022-07-29 00:18:05
```

</details>

### OS version

<details>

```console
# On Linux:
bash-5.1$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
$ uname -a
Linux emqx-0 5.15.45-1-virt #2-Alpine SMP Mon, 06 Jun 2022 10:19:37 +0000 x86_64 Linux

Note this is just a worker node in my K3s kubernetes cluster.
```

</details>

### Log files

<details>
unrelated to issue
</details>

**Comment by Rory-Z** [comment]
Hi, @ryphon Sorry for delay
I tried to deploy crd and it worked
```
$ kubectl apply -f apps.emqx.io_emqxbrokers.yaml --server-side --dry-run=server
customresourcedefinition.apiextensions.k8s.io/emqxbrokers.apps.emqx.io serverside-applied (server dry run)
```
Is there anything else I need to know?

**Comment by ryphon** [comment]
Hi @Rory-Z, I'm sure you're busy, appreciate the response. Try applying a broker object itself, similar to:

`apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx/emqx:4.4.0
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 512Mi
  emqxTemplate:
    listener:
      type: LoadBalancer
      ports:
        mqtt: 1883
        mqtts: 8883
        ws: 8083
        wss: 8084
        dashboard: 18083
        api: 8081
    acl:
      - permission: allow`

And then once you do the apply, wait for it to be healthy, and then run the apply again but with --server-side and --dry-run=server.

**Comment by Rory-Z** [comment]
Hi @ryphon I deploy EMQX Broker custom resource like you said and it is working fine.
```
$ cat << "EOF" | kubectl apply -f -
  apiVersion: apps.emqx.io/v1beta3
  kind: EmqxBroker  
  metadata:
    name: emqx 
  spec:                      
    emqxTemplate:   
      image: emqx/emqx:4.4.6
EOF
emqxbroker.apps.emqx.io/emqx created
```

Waiting EMQX cluster ready
```
$ kubectl get emqxbroker emqx -o json | jq '.status.conditions'
[
  {
    "lastTransitionTime": "2022-08-11T03:35:12Z",
    "lastUpdateTime": "2022-08-11T03:36:20Z",
    "message": "All resources are ready",
    "reason": "ClusterReady",
    "status": "True",
    "type": "Running"
  },
  {
    "lastTransitionTime": "2022-08-11T03:34:17Z",
    "lastUpdateTime": "2022-08-11T03:34:17Z",
    "message": "All default plugins initialized",
    "reason": "PluginInitializeSuccessfully",
    "status": "True",
    "type": "PluginInitialized"
  }
]
```

And run the apply again

```
$ cat << "EOF" | kubectl apply --server-side --dry-run=server -f -
  apiVersion: apps.emqx.io/v1beta3
  kind: EmqxBroker
  metadata:
    name: emqx
  spec:
    emqxTemplate:
      image: emqx/emqx:4.4.6
EOF
emqxbroker.apps.emqx.io/emqx serverside-applied (server dry run)
```

I'm using EMQX Operator 1.2.5 by helm chart 1.0.10
```
$ helm ls -n emqx-operator-system
NAME            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
emqx-operator   emqx-operator-system    2               2022-08-11 11:34:04.397264 +0800 CST    deployed        emqx-operator-1.0.10    1.2.5      
```

**Comment by ryphon** [comment]
Huh, guess I was on an older version than I thought. Updated to helm chart 1.0.10, app version 1.2.5, and updated my broker spec from v1beta2 -> v1beta3 + some of the template changes. Seems to work great now.

Big thanks for the help, great product!

**Comment by Rory-Z** [comment]
Coooool
