### ISSUE TITLE
Is it possible to add and delete through HTTP API

### ISSUE THREAD

**Issue by Slideee** [emqx/emqx-operator#357]
After acl.conf is mounted to /mounted/acl/acl.conf by the operator, is the native ACL HTTP API unavailable?

At the same time, after changing the acl configuration by modifying the acl field under the spec, you need to reload the acl module before the corresponding rules take effect. is that so?

- emqx-operator version:  1.2.1

**Comment by Slideee** [comment]
The interface can only query the ACL data added by the HTTP API
<img width="594" alt="image" src="https://user-images.githubusercontent.com/48793283/187593353-fd840efb-f726-48a8-87a6-ccdf10c53521.png">

In fact, the ACL configuration in the path I mounted, and the ACL rules added through the HTTP API do not exist under /mounted/acl/acl.conf
<img width="483" alt="image" src="https://user-images.githubusercontent.com/48793283/187593397-3050bcb9-1c74-4e3d-8e53-7e104ca11003.png">

**Comment by Rory-Z** [comment]
Hi， @Slideee could you please update operator version to 1.2.5 and retry it ?

**Comment by Slideee** [comment]
> Hi， @Slideee could you please update operator version to 1.2.5 and retry it ? If If this problem persists, please let me know the version of EMQX deployed

emqx version: 4.3.12 , I'll test 1.2.5 later

**Comment by Rory-Z** [comment]
Hi @Slideee We have just release 1.2.6, and you can try it. 
About EMQX,  we recommend using 4.4.8
Please let me know if you are using the Enterprise version of EMQX or the Community version of EMQX

**Comment by Slideee** [comment]
> Hi @Slideee We have just release 1.2.6, and you can try it. About EMQX, we recommend using 4.4.8 Please let me know if you are using the Enterprise version of EMQX or the Community version of EMQX

OK， Community EMQX 4.3.12
