### ISSUE TITLE
Cannot login to dashboard

### ISSUE THREAD

**Issue by fabltd** [emqx/emqx-operator#384]
**Describe the bug**
Dash board reports - some error occoured

Logs show:

`2022-09-12 11:41:09.622 BST2022-09-12T10:41:09.621898+00:00 [warning] exception: error, line: 116, mfa: minirest_handler:apply_callback/3, path: /listeners, reason: {badmatch,{error,{'EXIT',{{badkey,<<"listeners">>},[{erlang,map_get,[<<"listeners">>,#{}],[{error_info,#{module => erl_erts_errors}}]},{emqx_config,get_schema_mod,1,[{file,"emqx_config.erl"},{line,505}]},{emqx_listeners,do_list_raw,0,[{file,"emqx_listeners.erl"},{line,92}]},{emqx_listeners,list_raw,0,[{file,"emqx_listeners.erl"},{line,71}]},{emqx_mgmt_api_listeners,do_list_listeners,0,[{file,"emqx_mgmt_api_listeners.erl"},{line,519}]}]}}}}, stacktrace: [{emqx_mgmt_api_listeners,listener_status_by_id,2,[{file,"emqx_mgmt_api_listeners.erl"},{line,496}]},{emqx_mgmt_api_listeners,listener_status_by_id,1,[{file,"emqx_mgmt_api_listeners.erl"},{line,472}]},{emqx_mgmt_api_listeners,list_listeners,2,[{file,"emqx_mgmt_api_listeners.erl"},{line,342}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,111}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,44}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]`

**To Reproduce**

Followed installation steps in Google K8s - GKE

Attepted to portforward to the dashboard and login with admin / public

**Expected behavior**
To be able to login.

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version:

1.22.11-gke.400

- Cloud-provider/provisioner:

Google Cloud

- emqx-operator version: 

V5

- Install method: e.g. helm/static manifests

https://github.com/emqx/emqx-operator/blob/main/docs/en_US/getting-started/getting-started.md

**Comment by Rory-Z** [comment]
Hi, @fabltd Could you please share your EMQX Custom Resource YAML file ? like `https://github.com/emqx/emqx-operator/blob/2.0.0/config/samples/emqx/v2alpha1/emqx-full.yaml`

**Comment by fabltd** [comment]
Hi Rory 

I just used the example here:
```

cat << "EOF" | kubectl apply -f -
  apiVersion: apps.emqx.io/v2alpha1
  kind: EMQX
  metadata:
    name: emqx
  spec:
    image: emqx/emqx:5.0.6
EOF

```
I have made no attempt to customise. Yet

Then ran:

`k port-forward service/emqx-dashboard 18083:18083 `

Attempted to login to the dashboard it reports `Some Error`

Logs showing the error. 

I am now not able to progress.

Thank you

**Comment by Rory-Z** [comment]
Hi, @fabltd Does this error log only appear once, or does it appear every time log in?

**Comment by fabltd** [comment]
Every attempt to login.

I have never been able to login.

**Comment by fabltd** [comment]
If you let me know a way to contact you I can give you access to the cluster?

**Comment by fabltd** [comment]
Also what is the purpose of this annotation:


`banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAA.........`

**Comment by Rory-Z** [comment]
Could you please run `emqx eval  "persistent_term:get({emqx_config, schema_mods})."` in EMQX pods ? And please let me know outputs

**Comment by Rory-Z** [comment]
> Also what is the purpose of this annotation:
> 
> `banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAA.........`

This annotation is used by the EMQX Operator to determine if a resource needs to be updated, and you can ignore it

**Comment by fabltd** [comment]
I have 6 pods running 3 core pods and 3 replicant pods.

Can you confirm the full command to run?

**Comment by fabltd** [comment]
Assuming you mean a kubectl exec I got the following:

**emqx-core-0**

```
#{mods =>
      #{<<"retainer">> => emqx_conf_schema,<<"exhook">> => emqx_conf_schema,
        <<"log">> => emqx_conf_schema,<<"prometheus">> => emqx_conf_schema,
        <<"force_gc">> => emqx_conf_schema,<<"alarm">> => emqx_conf_schema,
        <<"plugins">> => emqx_conf_schema,
        <<"psk_authentication">> => emqx_conf_schema,
        <<"gateway">> => emqx_conf_schema,
        <<"authorization">> => emqx_conf_schema,
        <<"broker">> => emqx_conf_schema,<<"bridges">> => emqx_conf_schema,
        <<"topic_metrics">> => emqx_conf_schema,
        <<"sys_topics">> => emqx_conf_schema,
        <<"flapping_detect">> => emqx_conf_schema,
        <<"rule_engine">> => emqx_conf_schema,
        <<"cluster">> => emqx_conf_schema,<<"dashboard">> => emqx_conf_schema,
        <<"stats">> => emqx_conf_schema,
        <<"conn_congestion">> => emqx_conf_schema,
        <<"auto_subscribe">> => emqx_conf_schema,
        <<"authentication">> => emqx_conf_schema,
        <<"rewrite">> => emqx_conf_schema,<<"trace">> => emqx_conf_schema,
        <<"force_shutdown">> => emqx_conf_schema,
        <<"delayed">> => emqx_conf_schema,<<"node">> => emqx_conf_schema,
        <<"connectors">> => emqx_conf_schema,
        <<"limiter">> => emqx_conf_schema,<<"rpc">> => emqx_conf_schema,
        <<"mqtt">> => emqx_conf_schema,<<"listeners">> => emqx_conf_schema,
        <<"sysmon">> => emqx_conf_schema,
        <<"persistent_session_store">> => emqx_conf_schema,
        <<"overload_protection">> => emqx_conf_schema,
        <<"telemetry">> => emqx_conf_schema,<<"statsd">> => emqx_conf_schema,
        <<"zones">> => emqx_conf_schema,<<"slow_subs">> => emqx_conf_schema},
  names =>
      [<<"alarm">>,<<"authentication">>,<<"authorization">>,
       <<"auto_subscribe">>,<<"bridges">>,<<"broker">>,<<"cluster">>,
       <<"conn_congestion">>,<<"connectors">>,<<"dashboard">>,<<"delayed">>,
       <<"exhook">>,<<"flapping_detect">>,<<"force_gc">>,<<"force_shutdown">>,
       <<"gateway">>,<<"limiter">>,<<"listeners">>,<<"log">>,<<"mqtt">>,
       <<"node">>,<<"overload_protection">>,<<"persistent_session_store">>,
       <<"plugins">>,<<"prometheus">>,<<"psk_authentication">>,<<"retainer">>,
       <<"rewrite">>,<<"rpc">>,<<"rule_engine">>,<<"slow_subs">>,<<"stats">>,
       <<"statsd">>,<<"sys_topics">>,<<"sysmon">>,<<"telemetry">>,
       <<"topic_metrics">>,<<"trace">>,<<"zones">>]}
```

**emxq-core-1**

```
#{mods =>
      #{<<"retainer">> => emqx_conf_schema,<<"exhook">> => emqx_conf_schema,
        <<"log">> => emqx_conf_schema,<<"prometheus">> => emqx_conf_schema,
        <<"force_gc">> => emqx_conf_schema,<<"alarm">> => emqx_conf_schema,
        <<"plugins">> => emqx_conf_schema,
        <<"psk_authentication">> => emqx_conf_schema,
        <<"gateway">> => emqx_conf_schema,
        <<"authorization">> => emqx_conf_schema,
        <<"broker">> => emqx_conf_schema,<<"bridges">> => emqx_conf_schema,
        <<"topic_metrics">> => emqx_conf_schema,
        <<"sys_topics">> => emqx_conf_schema,
        <<"flapping_detect">> => emqx_conf_schema,
        <<"rule_engine">> => emqx_conf_schema,
        <<"cluster">> => emqx_conf_schema,<<"dashboard">> => emqx_conf_schema,
        <<"stats">> => emqx_conf_schema,
        <<"conn_congestion">> => emqx_conf_schema,
        <<"auto_subscribe">> => emqx_conf_schema,
        <<"authentication">> => emqx_conf_schema,
        <<"rewrite">> => emqx_conf_schema,<<"trace">> => emqx_conf_schema,
        <<"force_shutdown">> => emqx_conf_schema,
        <<"delayed">> => emqx_conf_schema,<<"node">> => emqx_conf_schema,
        <<"connectors">> => emqx_conf_schema,
        <<"limiter">> => emqx_conf_schema,<<"rpc">> => emqx_conf_schema,
        <<"mqtt">> => emqx_conf_schema,<<"listeners">> => emqx_conf_schema,
        <<"sysmon">> => emqx_conf_schema,
        <<"persistent_session_store">> => emqx_conf_schema,
        <<"overload_protection">> => emqx_conf_schema,
        <<"telemetry">> => emqx_conf_schema,<<"statsd">> => emqx_conf_schema,
        <<"zones">> => emqx_conf_schema,<<"slow_subs">> => emqx_conf_schema},
  names =>
      [<<"alarm">>,<<"authentication">>,<<"authorization">>,
       <<"auto_subscribe">>,<<"bridges">>,<<"broker">>,<<"cluster">>,
       <<"conn_congestion">>,<<"connectors">>,<<"dashboard">>,<<"delayed">>,
       <<"exhook">>,<<"flapping_detect">>,<<"force_gc">>,<<"force_shutdown">>,
       <<"gateway">>,<<"limiter">>,<<"listeners">>,<<"log">>,<<"mqtt">>,
       <<"node">>,<<"overload_protection">>,<<"persistent_session_store">>,
       <<"plugins">>,<<"prometheus">>,<<"psk_authentication">>,<<"retainer">>,
       <<"rewrite">>,<<"rpc">>,<<"rule_engine">>,<<"slow_subs">>,<<"stats">>,
       <<"statsd">>,<<"sys_topics">>,<<"sysmon">>,<<"telemetry">>,
       <<"topic_metrics">>,<<"trace">>,<<"zones">>]}
```

**emqx-core-2**

```
#{mods =>
      #{<<"retainer">> => emqx_conf_schema,<<"exhook">> => emqx_conf_schema,
        <<"log">> => emqx_conf_schema,<<"prometheus">> => emqx_conf_schema,
        <<"force_gc">> => emqx_conf_schema,<<"alarm">> => emqx_conf_schema,
        <<"plugins">> => emqx_conf_schema,
        <<"psk_authentication">> => emqx_conf_schema,
        <<"gateway">> => emqx_conf_schema,
        <<"authorization">> => emqx_conf_schema,
        <<"broker">> => emqx_conf_schema,<<"bridges">> => emqx_conf_schema,
        <<"topic_metrics">> => emqx_conf_schema,
        <<"sys_topics">> => emqx_conf_schema,
        <<"flapping_detect">> => emqx_conf_schema,
        <<"rule_engine">> => emqx_conf_schema,
        <<"cluster">> => emqx_conf_schema,<<"dashboard">> => emqx_conf_schema,
        <<"stats">> => emqx_conf_schema,
        <<"conn_congestion">> => emqx_conf_schema,
        <<"auto_subscribe">> => emqx_conf_schema,
        <<"authentication">> => emqx_conf_schema,
        <<"rewrite">> => emqx_conf_schema,<<"trace">> => emqx_conf_schema,
        <<"force_shutdown">> => emqx_conf_schema,
        <<"delayed">> => emqx_conf_schema,<<"node">> => emqx_conf_schema,
        <<"connectors">> => emqx_conf_schema,
        <<"limiter">> => emqx_conf_schema,<<"rpc">> => emqx_conf_schema,
        <<"mqtt">> => emqx_conf_schema,<<"listeners">> => emqx_conf_schema,
        <<"sysmon">> => emqx_conf_schema,
        <<"persistent_session_store">> => emqx_conf_schema,
        <<"overload_protection">> => emqx_conf_schema,
        <<"telemetry">> => emqx_conf_schema,<<"statsd">> => emqx_conf_schema,
        <<"zones">> => emqx_conf_schema,<<"slow_subs">> => emqx_conf_schema},
  names =>
      [<<"alarm">>,<<"authentication">>,<<"authorization">>,
       <<"auto_subscribe">>,<<"bridges">>,<<"broker">>,<<"cluster">>,
       <<"conn_congestion">>,<<"connectors">>,<<"dashboard">>,<<"delayed">>,
       <<"exhook">>,<<"flapping_detect">>,<<"force_gc">>,<<"force_shutdown">>,
       <<"gateway">>,<<"limiter">>,<<"listeners">>,<<"log">>,<<"mqtt">>,
       <<"node">>,<<"overload_protection">>,<<"persistent_session_store">>,
       <<"plugins">>,<<"prometheus">>,<<"psk_authentication">>,<<"retainer">>,
       <<"rewrite">>,<<"rpc">>,<<"rule_engine">>,<<"slow_subs">>,<<"stats">>,
       <<"statsd">>,<<"sys_topics">>,<<"sysmon">>,<<"telemetry">>,
       <<"topic_metrics">>,<<"trace">>,<<"zones">>]
```

The output appears to be the same for each of the replicant pods

**Comment by Rory-Z** [comment]
@zhongwencool Anything ideas ?

**Comment by zhongwencool** [comment]
Thanks for all detail messages :0

The `emqx eval "persistent_term:get({emqx_config, schema_mods})."` results are ok.

What happened when you login in now?
the crash log `exception: error, line: 116, mfa: minirest_handler:apply_callback/3, path: /listeners, reason: {badmatch,{error,{'EXIT',{{badkey,` Should not appear anymore.

**Comment by fabltd** [comment]
I have removed and rebuild the k8s cluster. Re installed.

Still same error:` Some error occurred`

And same error message:

Info
`2022-09-13 05:00:36.056 BST2022-09-13T04:00:36.055746+00:00 [warning] exception: error, line: 116, mfa: minirest_handler:apply_callback/3, path: /listeners, reason: {badmatch,{error,{'EXIT',{{badkey,<<"listeners">>},[{erlang,map_get,[<<"listeners">>,#{}],[{error_info,#{module => erl_erts_errors}}]},{emqx_config,get_schema_mod,1,[{file,"emqx_config.erl"},{line,505}]},{emqx_listeners,do_list_raw,0,[{file,"emqx_listeners.erl"},{line,92}]},{emqx_listeners,list_raw,0,[{file,"emqx_listeners.erl"},{line,71}]},{emqx_mgmt_api_listeners,do_list_listeners,0,[{file,"emqx_mgmt_api_listeners.erl"},{line,519}]}]}}}}, stacktrace: [{emqx_mgmt_api_listeners,listener_status_by_id,2,[{file,"emqx_mgmt_api_listeners.erl"},{line,496}]},{emqx_mgmt_api_listeners,listener_status_by_id,1,[{file,"emqx_mgmt_api_listeners.erl"},{line,472}]},{emqx_mgmt_api_listeners,list_listeners,2,[{file,"emqx_mgmt_api_listeners.erl"},{line,342}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,111}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,44}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]`

**Comment by fabltd** [comment]
@zhongwencool let me know if you want access to the cluster I can email you to arrange.

JT

**Comment by fabltd** [comment]
Attached is the complete log from the new cluster.

There are some other interesting log enteries:

`[warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms"` 

`[warning] line: 121, mfa: mria:stop/1, msg: Stopping mria, reason: join`

[downloaded-logs-20220913-050731.json.zip](https://github.com/emqx/emqx-operator/files/9553432/downloaded-logs-20220913-050731.json.zip)

**Comment by zhongwencool** [comment]
> Attached is the complete log from the new cluster.
> 
> There are some other interesting log enteries:
> 
> `[warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms"`
> 
> `[warning] line: 121, mfa: mria:stop/1, msg: Stopping mria, reason: join`
> 
> [downloaded-logs-20220913-050731.json.zip](https://github.com/emqx/emqx-operator/files/9553432/downloaded-logs-20220913-050731.json.zip)



> @zhongwencool let me know if you want access to the cluster I can email you to arrange.
> 
> JT

Please  send it to zhongwen.deng[at]emqx.io.

**Comment by fabltd** [comment]
Thank you

I am just looking the the config and I note the following:

bootstrapConfig string | EMQX bootstrap config, hocon style, like emqx.conf Cannot be updated.

How do you make config changes once the install is deployed?

**Comment by Rory-Z** [comment]
> How do you make config changes once the install is deployed?

In our design, this can be modified via the EMQX Dashboard, but in this issue, you can't log in EMQX Dashboard

**Comment by fabltd** [comment]
Thanks

Whats the difference between the core pods and the replicant pods?

**Comment by Rory-Z** [comment]
> Whats the difference between the core pods and the replicant pods?

Maybe this can be help: https://www.emqx.com/en/blog/how-emqx-5-0-achieves-100-million-mqtt-connections

**Comment by fabltd** [comment]
Thanks

Is there some docs on configing the options for the listenersServiceTemplate ? 

I.E how to set up for MQTTS ? 

Can we provision a load balancer from here. I am wondering if my issue is related to networking configuration with port forwarding so I wanted to try cluster IP / Load Balancer.

**Comment by Rory-Z** [comment]
Hi， @fabltd, In fact, the `listenerServiceTemplate` is the k8s service resource, so you can set `listenerServiceTemplate.spec.type: LoadBalancer` like service resource

**Comment by fabltd** [comment]
Hi Rory

Ok somthing doesn't work with Google Cloud Shell port forwarding. Now I have a nodeport exposed the dashboard is working.

How do I enable MQTTS I see how to add the listerner in the dashboard but how do I define it in the yaml?

**Comment by Rory-Z** [comment]
> How do I enable MQTTS I see how to add the listerner in the dashboard but how do I define it in the yaml?

Two ways:

1. You can add listeners by EMQX Dashboard, the EMQX Operator will update service for add listener port
2. You can set `listeners.ssl.default.bind` to `bootstrapConfig` in EMQX Custom Resource YAML file, for more configuration details, please check emqx's `etc/emqx-example.conf`

**Comment by fabltd** [comment]
Thnaks I noted its updating the loadbalncer. I just need to provision some certs to test.

Point 2 - That still only applies on inital config cannot be updated after?

**Comment by Rory-Z** [comment]
>  I just need to provision some certs to test.

You can create tls secret resource, and use `.replicantTemplate.spec.extraVolume` and `.replicantTemplate.spec.extraVolumeMount` to mount to EMQX container.

I recommend that you use the EMQX Dashboard directly, which will allow you to upload your certs

> Point 2 - That still only applies on inital config cannot be updated after?
Yes.
