### ISSUE TITLE
Need a method to setting private image registry for emqx-operator-reloader image

### ISSUE THREAD

**Issue by wooonderful** [emqx/emqx-operator#433]
**Describe the solution you'd like**
We install emqx-operator by helm or yaml, but both have no method to setting the private registry for   emqx-operator-reloader image.

**Describe alternatives you've considered**
the emqx-operator-reloader image's registry should be same to emqx-operator-controller's registry.

**Comment by Rory-Z** [comment]
> the emqx-operator-reloader image's registry should be same to emqx-operator-controller's registry.

Hi, @wooonderful, I think the `emqx-operator-reloader` image's registry should can be user-defined in EMQX CR File, this has nothing to do with `emqx-operator-controller`, what do you think ?

**Comment by wooonderful** [comment]
> > the emqx-operator-reloader image's registry should be same to emqx-operator-controller's registry.
> 
> Hi, @wooonderful, I think the `emqx-operator-reloader` image's registry should can be user-defined in EMQX CR File, this has nothing to do with `emqx-operator-controller`, what do you think ?

<img width="515" alt="image" src="https://user-images.githubusercontent.com/115449150/199173637-1d6d8dca-2d04-41a6-8609-94a93bb2bb84.png">
thanks for your reply, now the helm value.yaml file has repository feild, I think this field should be the private registry url, eg: "https://hub-mirror.c.163.com", "https://dockerhub.azk8s.cn"

**Comment by ssfdust** [comment]
https://github.com/emqx/emqx-operator/blob/a274cd4d34aee134b62fcf3ec8100a2cb1f74a56/controllers/apps/v1beta3/emqx_handler.go#L723
这里写死了`ReloaderContainerImage`，应该提供一个`instance.getReloaderImage`的方法，让用户自定义reloader image地址。

现在的临时方案就是在operator生成statefulset之后，把statefulset的reloader image给patch掉。

**Comment by Rory-Z** [comment]
EMQX Operator 1.2.8 and EMQX Operator 2.0.2 already support this
