### ISSUE TITLE
Error creating CRD when reusing helm install on different namespaces

### ISSUE THREAD

**Issue by dberardo-com** [emqx/emqx-operator#452]
The first time i run helm install everything goes smoothly, i.e. the CRD are installed and all the rest deployed.

when i run helm install on a different namespace, setting the value skipCRDs to true, i get an error of ownership in the cluster role ... how to fix?

**Comment by dberardo-com** [comment]
ok i got it, i have to set 

serviceAccount:
  create: false

but now i get an error with the annotation MutatingWebhookConfiguration helm.release which is not matching the new namespace

**Comment by Rory-Z** [comment]
You only need to install Operator once and it can manage emqx in different namespaces

**Comment by dberardo-com** [comment]
thanks for the reply. I will take note of it.

I am not fully aware of which version i am using, but i know i am using the chart v2.0.1 from https://repos.emqx.io/charts and to setup the cluster i am using the EMQX  CRD, not EMQBroker, so i guess i am using v5 - 2lapha1 , am i correct?

**Comment by Rory-Z** [comment]
> I am not fully aware of which version i am using, but i know i am using the chart v2.0.1 from https://repos.emqx.io/charts and to setup the cluster i am using the EMQX CRD, not EMQBroker, so i guess i am using v5 - 2lapha1 , am i correct?

This depends on the version of EMQX you are deploying, in `v2alpha1` we use `kind: EMQX` to deploy EMQX 5, in `v1beta3` we use `kind: EmqxBroker` to deploy the community version of EMQX 4, and `kind: EmqxEnterprise` to deploy the enterprise version of EMQX 4

**Comment by Rory-Z** [comment]
> basically my second question on how to create users via the operator boils down to the more generic question: what can we do with the operator at all? "just" controlling the cluster nodes or also ACL, topics, configs, etc?

In addition to this, EMQX Operator also offers a number of operational and maintenance features. For example, when you update the EMQX listener using the EMQX 5 Dashboard, the EMQX Operator will automatically update the K8S service

**Comment by dberardo-com** [comment]
> In addition to this, 

so you mean that creating ACL and topics is possible via defining the right CRD?  is there any documentation for that ?

**Comment by dberardo-com** [comment]
i think this issue can be closed and our discussion moved to: https://github.com/emqx/emqx-operator/issues/451#issuecomment-1309888092

**Comment by Rory-Z** [comment]
> i think this issue can be closed and our discussion moved to: [#451 (comment)](https://github.com/emqx/emqx-operator/issues/451#issuecomment-1309888092)

OK, let me close this issue
