### ISSUE TITLE
emqx-operator-webhook-service has vague spec selectors 

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/emqx-operator#486]
**Describe the bug**
The original emqx-operator-webhook-service has the following config:
```
spec:
  selector:                                                                                                                                                │
    control-plane: controller-manager 
```
which is too vague. On my k8s cluster, with additional operators installed this service selector targets also other operator pods causing problems when the request goes to other operators.

**To Reproduce**
- have another pod with label: control-plane: controller-manager, for example, deploy emqx operator in a namespace in which a grafana operator exists(https://github.com/grafana-operator/grafana-operator).

**Expected behavior**
The service selector for the webhook service should be more restrictive, for example:
```
spec:
  selector:                                                                                                                                                │
    control-plane: controller-manager
    app.kubernetes.io/name: emqx-operator
```

**Environment details:**:
- Kubernetes version:  v1.22.15-gke.100
- Cloud-provider/provisioner: GKE
- emqx-operator version: 2.0.1
- Install method: helm

**Comment by mariusstaicu** [comment]
not sure if this is a bug or enhancement though

**Comment by Rory-Z** [comment]
Yes, it's my bad, and after Operator 2.0, we recommend using Helm to deploy EMQX Operator, which avoids similar problems
