### ISSUE TITLE
Downscale core nodes

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx-operator#629]
### Discussed in https://github.com/emqx/emqx-operator/discussions/628

<div type='discussions-op-text'>

<sup>Originally posted by **alexa22013** February 27, 2023</sup>
When I downscaled core nodes from 3 to 2 the repicant nodes were crashing 

replicant node logs showed this error
`
[emqx-replicant-6d5577f77d-lx4: 2023-02-26T19:08:47.518993+00:00 [error] line: 182, mfa: mria_lb:list_core_nodes/1, msg: mria_lb_core_discovery divergent cluster, node: 'emqx@10.237.115.78', previous_cores: [], returned_cores: ['emqx@emqx-core-0.emqx-headless.emqx.svc.cluster.local','emqx@emqx-core-1.emqx-headless.emqx.svc.cluster.local'], unknown_nodes: ['emqx@emqx-core-2.emqx-headless.emqx.svc.cluster.local']]
`
how to avoid this?

Also is there any practice on when to scale core node and when to scale replicants?
</div>

**Comment by HJianBo** [comment]
it's maybe an issue. So invite @ieQu1 to help with the investigation
I had some discussions with @Rory-Z there are some key points:
- Clustering via DNS
- The Operator just shut down the core node in downscaling, instead of executing the `emqx ctl cluster leave` cmd and waiting for its completion.

**Comment by Rory-Z** [comment]
> it's maybe an issue. So invite @ieQu1 to help with the investigation I had some discussions with @Rory-Z there are some key points:
> 
> * Clustering via DNS
> * The Operator just shut down the core node in downscaling, instead of executing the `emqx ctl cluster leave` cmd and waiting for its completion.

And after downscale code nodes, the DNS list will updated

**Comment by ieQu1** [comment]
Fixed by https://github.com/emqx/mria/pull/123/files

**Comment by Rory-Z** [comment]
> Fix https://github.com/emqx/mria/pull/123/files

Do we plan to introduce this fix in `EMQX 5.0.19` and `EMQX Enterprise 5.0.1` ?

**Comment by Rory-Z** [comment]
[EMQX 5.0.19 is released](https://github.com/emqx/emqx/releases/tag/v5.0.19), close this issue.
