### ISSUE TITLE
EMQX Users migration between v4.3.17 to v5 with operator 

### ISSUE THREAD

**Issue by memoliyasti** [emqx/emqx-operator#653]
Hello all,

I would like to hear your suggestion about EMQX users migration.
We are planning to upgrade emqx version and use it with operator.

What is the best way of migrating existing users from emqx v4 to v5. We are going to use emqx with operator.

I would like to hear your suggestions.

Thank you.

**Comment by Rory-Z** [comment]
Hi, @memoliyasti Sorry, you cannot upgrade from EMQX v4 to v5 now. You need to create a new EMQX cluster.
First, you need install EMQX Operator 2.1, and use `apiVersion: apps.emqx.io/v2alpha1` and `kind: EMQX` to deploy EMQX cluster, like https://github.com/emqx/emqx-operator/blob/main/config/samples/emqx/v2alpha1/emqx-slim.yaml.
Second, you can check [migrate from V4 in EMQX document](https://www.emqx.io/docs/en/v5.0/deploy/upgrade-from-v4.html)

**Comment by memoliyasti** [comment]
Hello @Rory-Z , thanks for quick reply.
Let me describe the situation we have. 
Along with upgrading broker itself, we want to migrate existing users from emqx v4 (non-operator) to emqx v5 (operator version).
We are able to run v5 with operator but we like to know how to take these users out which are located in v4 to the v5 (with operator)? This is the v4 [chart](https://github.com/emqx/emqx/tree/master/deploy/charts/emqx) we have. 

Thank you.

**Comment by Rory-Z** [comment]
> Along with upgrading broker itself, we want to migrate existing users from emqx v4 (non-operator) to emqx v5 (operator version).

Hi @memoliyasti please define "existing users" first, I guess this is MQTT client ?

**Comment by Rory-Z** [comment]
Unfortunately, you can only create a new EMQX cluster and migrate the MQTT Client connections to the new cluster. During this process, you can use certain routing methods to make the operation easier. Please note that newly created connections by MQTT Clients do not contain any session information and they need to subscribe to topics again.
