### ISSUE TITLE
extraContainers field no longer available in CRD in v2.1.2

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/emqx-operator#773]
It seems that spec.coreTemplate.spec.extraContainers field was lost in the last update (2.1.2).

**To Reproduce**

1. Have an emqx resource with an extra container  declared in spec.coreTemplate.spec.extraContainers.
2. upgrade to latest emqx-operator v2.1.2
3. extra container will no longer be created by operator

**Expected behavior**
The extra container should be present even after the upgrade.

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: v1.24.10-gke.2300
- Cloud-provider/provisioner: GKE
- emqx-operator version: v2.1.2
- Install method: helm

**Comment by Rory-Z** [comment]
Hi, @mariusstaicu sorry for delay.
What was the version of EMQX Operator before the upgrade? Is it 2.1.1?
And could you please show the EMQX custom resource YAML file, It's very helpful for me

**Comment by mariusstaicu** [comment]
first I did 2.1.0 -> 2.1.2 and this bug presented. 
Then I did 2.1.0 -> 2.1.1 and it worked. Then, when I did 2.1.1 -> 2.1.2 it didn't work anymore again.

**Comment by mariusstaicu** [comment]
I will add the yaml file soon, however I need to remove sensitive info from it.

**Comment by Rory-Z** [comment]
> I will add the yaml file soon, however I need to remove sensitive info from it.

I'm looking forward

**Comment by mariusstaicu** [comment]
Also when I try to reapply the resource with the operator v2.1.2 installed I get the following error:
`error: error validating "1-emqx.yml": error validating data: ValidationError(EMQX.spec.coreTemplate.spec): unknown field "extraContainers" in io.emqx.apps.v2alpha1.EMQX.spec.coreTemplate.spec; if you choose to ignore these errors, turn validation off with --validate=false
`

**Comment by Rory-Z** [comment]
Hi, @mariusstaicu Sorry for delay, this is a bug, let me fix it.

**Comment by Rory-Z** [comment]
Hi @mariusstaicu the EMQX Operator 2.1.3 is released, and this bug has fixed.
I will close this issue, if you have any question,  you can reopen it
