### ISSUE TITLE
Multiple node emqx-ee cluster will be not available for use, even if just one node error.

### ISSUE THREAD

**Issue by wooonderful** [emqx/emqx-operator#802]
**Describe the bug**
I have a three node emqx-ee cluster that created by emqx-opeartor which 1.2.7 version;
When just one node running failed for some reason, for example,  file direction permission,  My whole emqx-ee cluster will be inaccessible， for the 1883\8883 ports will be disappear in the default service.

<img width="890" alt="image" src="https://github.com/emqx/emqx-operator/assets/115449150/c84151ee-464a-49cf-85ba-d5fe593fc852">

**To Reproduce**
1. create  a multiple node emqx-ee cluster;
2. get into one node, change the data direction permission to 400;
3. watch the default service's change.

**Expected behavior**
just part of node running failed, the emqx-ee cluster should be also accessible.
the service also should be like as the blow example:
<img width="1071" alt="image" src="https://github.com/emqx/emqx-operator/assets/115449150/bc0f5c0d-8118-40a7-9ae8-74bd5b2ef9c5">

**Anything else we need to know?**:
the latest emqx-operator version also has this same problem.

**Environment details:**:
- Kubernetes version: 1.22.3
- emqx-operator version: 1.2.7-ecp.1 
- Install method: e.g. helm/static manifests helm

**Comment by Rory-Z** [comment]
Hi, @wooonderful Sorry for delay, the EMQX Operator 1.2.7 is too old, could you please try 2.2.0?

**Comment by wooonderful** [comment]
> Hi, @wooonderful Sorry for delay, the EMQX Operator 1.2.7 is too old, could you please try 2.2.0?

ok

**Comment by Rory-Z** [comment]
Hi @wooonderful Is your issue still there?

**Comment by wooonderful** [comment]
> Hi @wooonderful Is your issue still there?

yes, it is still a problem for us until we upgrade to 2.x. But, the upgrade maybe will be done in the Q4.

**Comment by Rory-Z** [comment]
Hi @wooonderful the EMQX Operator 1.2.7-ec.2 is fixed this issue, could you please try it.
https://github.com/emqx/emqx-operator/releases/tag/1.2.7-ecp.2

I will close this issue, if you have any question, can reopen it in anytime
