### ISSUE TITLE
Cannot upgrade EMQX replicant image

### ISSUE THREAD

**Issue by webfrank** [emqx/emqx-operator#809]
**Describe the bug**
Not able to upgrade EMQX Replicant version

**To Reproduce**
Deploy a cluster with EMQX Operator 2.1.0, upgrade Operator to 2.1.3, change EMQX version from 5.0.14 to 5.0.26. The core get upgraded, the replicants sticks in mria cannot ping the nodes.

**Expected behavior**
A rolling upgrade of all nodes

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: 1.21
- Cloud-provider/provisioner: AWS
- emqx-operator version: 2.1.0 -> 2.1.3
- Install method: Helm

**Comment by Rory-Z** [comment]
Looks like same to https://github.com/emqx/emqx/issues/11071 ？

**Comment by Rory-Z** [comment]
@ieQu1 Could you please take a look, I see "Different Mria version on the core node", so Is the jump from 5.0.14 to 5.0.26 too big ?
@zmstone I remember you mentioned this risk to me, right?

**Comment by mariusstaicu** [comment]
I jumped from 5.0.17 to 5.0.26 today with no problems.

**Comment by ieQu1** [comment]
Hello all,

Mria (our embedded DB) sometimes has incompatible changes in the protocol. In order to prevent data corruption, replicant nodes will refuse to connect to the core node that doesn't run the compatible version.

Because of that, rolling upgrade of EMQX cluster should be done in batches. Let's assume we have N cores and M replicants. Stages of upgrade should look like this:
- Upgrade 1 core node of N
- Upgrade M/N replicants
- Repeat until all nodes are upgraded

When this procedure is used, the replicants will always have at least one core node that runs a compatible version of the code.

**Comment by webfrank** [comment]
Hi, i supposed was something like this but once the core get upgraded why
the new replicant does not connect? I agree the old replicants get
disconnected but not the new one, same version as the core.

Another point is how the operator handle this?

Il giorno sab 17 giu 2023 alle 11:24 ieQu1 ***@***.***> ha
scritto:

**Comment by Rory-Z** [comment]
Hi, @ieQu1 As far as I see, EMQX Operator didn't do this, but we are doing this part of the work.

In our current plan, we will first update the core node by rolling, and then update the replication node after all the core nodes are updated, which is also the plan suggested by @zmstone.

So is your proposed solution like this:
+ step1, create new core nodes and join cluster
+ step2, create new replicant nodes and join cluster
+ step3, wait all nodes ready
+ step4, delete old core nodes
+ step5, delete old replicant nodes

Do I understand it right?

**Comment by ieQu1** [comment]
Yes, this is correct.

**Comment by Rory-Z** [comment]
> Yes, this is correct.

In k8s, I usually manage core nodes as a set of Pods. In the first step above, if I create a new set of core node Pods to join the cluster, it may cause the number of core nodes to be multiplied by 2. Will this have any impact, especially if I cooperate with node evacuation to transfer MQTT connections?
