### ISSUE TITLE
Ability to configure serviceAccountName on core & replicant pods

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/emqx-operator#818]
**Is your feature request related to a problem? Please describe.**
We use emqx with postgres on cloud-sql. At the moment the cloudsql service account key file is mounted to the pods that require it and it works. However, we would very much like to switch to workload identity and it requires defining a service account on pods.

**Describe the solution you'd like**
The coreTemplateSpec and replicantTemplateSpec should have the possbility of defining **serviceAccountName**.

**Describe alternatives you've considered**
Not sure there is any with the current operator API v2alpha1.

**Additional context**

**Comment by Rory-Z** [comment]
Good idea！We will finish it，thanks

**Comment by Rory-Z** [comment]
EMQX Operator 2.2.0 is released, close this issue

**Comment by mariusstaicu** [comment]
great news, thanks
