### ISSUE TITLE
E0621 19:48:58.458958 8 controller.go:342] error processing service emqx-dashboard (will retry): Load balancer version unknown 

### ISSUE THREAD

**Issue by dylanlee085** [emqx/emqx-operator#819]
**Describe the bug**
use emqx-operator  2.1.4 deploy emqx:5.0 in huaweicloud cce cluster, the service emqx-dashboard can't  add listener to loadbalace,   the error message: E0621 19:48:58.458958 8 controller.go:342] error processing service emqx-dashboard (will retry): Load balancer version unknown
**To Reproduce**
use emqx-operator 2.1.4 deploy emqx 5.0  in huaweicloud cce cluster

**Expected behavior**
add listener to loadbalace successful

**Anything else we need to know?**:

**Environment details:**:  
- Kubernetes version: huaweicloud cce,   k8s version 1.23.8-r0
- Cloud-provider/provisioner: huaweicloud
- emqx-operator version:  2.1.4
- Install method: helm

**Comment by fabltd** [comment]
@dylanlee085  - Did you get the replicants and any load balancer for the  MQTT ports ? If not sounds like same issue I have

**Comment by dylanlee085** [comment]
1. i can get the replicants,  and  i can see the  container logs  the 1883, 8883, 8083, 18083 port is listen.
2. i create replicants and loadbalace  by yaml,  but now the  service emqx-listeners  with loadbalace is work ,  the  service emqx-dashboard is not work.   the k8s event:  error update loadbalancer   and   [error processing service emqx-dashboard (will retry): Load balancer version unknown](https://github.com/emqx/emqx-operator/issues/819#top)
3.  [the install doc ](https://docs.emqx.com/zh/emqx-operator/latest/deployment/on-huawei-cloud.html#%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2%E4%B8%80%E4%B8%AA-emqx-%E9%9B%86%E7%BE%A4)

**Comment by dylanlee085** [comment]
I got the emqx-dashboard SVC status and found that the extended IP is in a pending state

**Comment by Rory-Z** [comment]
> I got the emqx-dashboard SVC status and found that the extended IP is in a pending state

Could you please check the event of emqx-dashboard SVC ? I guess it is some reason from public cloud platform.

**Comment by dylanlee085** [comment]
this is the event of emqx-dashboard svc :
Events:
  Type     Reason                    Age                    From                Message
  ----     ------                    ----                   ----                -------
  Warning  UpdateLoadBalancerFailed  3m10s (x413 over 34h)  service-controller  error update loadbalancer

**Comment by dylanlee085** [comment]
1. I also gueses  it's some reaseon from public cloud platform , but i apply it in another cce cluster(1.23.7-r20) is work.  
2. I am unable to confirm whether the issue is caused by the different small versions of the CCE cluster. Additionally, I can successfully create an SVC with the same port associated with the load balancer directly through the cloud platform console, but creating it using the emqx operator fails

**Comment by Rory-Z** [comment]
Could you please check the EMQX Operator log and EMQX custom resource event ? Thanks.
