### ISSUE TITLE
Add links to rendered documentation

### ISSUE THREAD

**Issue by agronholm** [emqx/emqx-operator#901]
**Is your feature request related to a problem? Please describe.**

The GitHub repository should contain links to the rendered documentation. Given that there were none at all, I thought the sources were the only thing out there.

**Describe the solution you'd like**

At least a minimal mention of https://docs.emqx.com/en/emqx-operator/ somewhere at the top of the page.

**Describe alternatives you've considered**

**Additional context**

**Comment by Rory-Z** [comment]
Good idea, thanks
