### ISSUE TITLE
how to log into the dashboard through nodeport?

### ISSUE THREAD

**Issue by the-elder** [emqx/emqx-operator#935]
**Describe the bug**
use this tutorial  https://github.com/emqx/emqx-operator/blob/2.0.0/docs/zh_CN/getting-started/getting-started.md

 my deploy manifest:
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
   name: emqx
spec:
   image: emqx:5.1

**To Reproduce**
log into the dashbord through  IP:nodeport

**Comment by the-elder** [comment]
i try to change the service type for emqx-dashboard from ClusterIP to NodePort，it seems not work ,and the changes are being reverted。
![image](https://github.com/emqx/emqx-operator/assets/28731366/dbc1dc88-974e-4eca-b96d-91aa24ff88f0)
 a few moments later ....
![image](https://github.com/emqx/emqx-operator/assets/28731366/09e48b88-9909-46a5-84e3-63a51b0ac944)

**Comment by Rory-Z** [comment]
2.0.0 documents is too old, please check 2.2.1

**Comment by the-elder** [comment]
well ,i can not see any tips for nodePort with 2.2.1

**Comment by Rory-Z** [comment]
https://github.com/emqx/emqx-operator/blob/2.2.1/docs/zh_CN/tasks/configure-emqx-service.md
You can replace "LoadBalancer" with "NodePort" in the document.

**Comment by the-elder** [comment]
> https://github.com/emqx/emqx-operator/blob/2.2.1/docs/zh_CN/tasks/configure-emqx-service.md You can replace "LoadBalancer" with "NodePort" in the document.

thank you for reply
i tried this , but also got a question, why the nodeport keeps changing?
![image](https://github.com/emqx/emqx-operator/assets/28731366/4e91cb22-dddf-40fb-a01d-43e900a44847)
![image](https://github.com/emqx/emqx-operator/assets/28731366/508596d9-a3d3-44cb-9df8-28cbc0ff4dad)

**Comment by Rory-Z** [comment]
> why the nodeport keeps changing?

I guess your k8s version is lower than 1.21 ? Please check this: https://github.com/emqx/emqx-operator#how-to-selector-kubernetes-version

**Comment by the-elder** [comment]
> > why the nodeport keeps changing?
> 
> I guess your k8s version is lower than 1.21 ? Please check this: https://github.com/emqx/emqx-operator#how-to-selector-kubernetes-version

yes, k8s version 1.20

**Comment by Rory-Z** [comment]
@the-elder you can set nodePort in `.spec.listenersServiceTemplate.spec.ports[].nodePort` to avoid nodeport keeps changing

**Comment by the-elder** [comment]
> @the-elder you can set nodePort in `.spec.listenersServiceTemplate.spec.ports[].nodePort` to avoid nodeport keeps changing

it works, thank you!
