### ISSUE TITLE
Cannot install 5.1.[4,5,6] using the operator

### ISSUE THREAD

**Issue by webfrank** [emqx/emqx-operator#942]
**Describe the bug**
Cannot install 5.1.[4,5,6] using the operator. The last version working is 5.1.3

**To Reproduce**
Deploy a simple cluster with image emqx/emqx:5.1.5

**Expected behavior**
A working cluster

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: 1.21
- Cloud-provider/provisioner: AWS
- emqx-operator version: 2.2.2
- Install method: helm for operator and manifest for the cluster

Cluster Manifest

```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: "emqx/emqx:5.1.3"
  imagePullPolicy: IfNotPresent
  updateStrategy:
    evacuationStrategy:
      connEvictRate: 1000
      sessEvictRate: 1000
      waitTakeover: 10
    initialDelaySeconds: 10
    type: Recreate
  config: 
    data: |
      node {
        cookie = superSecretCookie
        data_dir = "data"
        etc_dir = "etc"
      }
      cluster {
        discovery_strategy = dns
        dns {
          record_type = srv
          name:"emqx-headless.emqx.svc.cluster.local"
        }
      }
      dashboard {
        listeners.http {
            bind: 18083
        }
        default_username: "admin"
        default_password: "public"
      }
      listeners.tcp.default {
        bind = "0.0.0.0:1883"
        max_connections = 1024000
      }
      sysmon.vm.long_schedule = disabled
  coreTemplate:
    metadata:
      name: emqx-core
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
      annotations:
    spec:
      replicas: 2
      volumeClaimTemplates:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce
      command:
        - "/usr/bin/docker-entrypoint.sh"
      args:
        - "/opt/emqx/bin/emqx"
        - "foreground"
      ports:
        - containerPort: 1883
        - name: metrics
          containerPort: 18083
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","emqx ctl cluster leave"]
  replicantTemplate:
    metadata:
      name: emqx-replicant
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: replicant
    spec:
      replicas: 3
      command:
        - "/usr/bin/docker-entrypoint.sh"
      args:
        - "/opt/emqx/bin/emqx"
        - "foreground"
      ports:
        - containerPort: 1883
        - name: metrics
          containerPort: 18083
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        supplementalGroups:
          - 1000
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 10
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 30
      startupProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 30
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","emqx ctl cluster leave"]
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
    spec:
      selector:
        apps.emqx.io/db-role: core
      ports:
        - name: "dashboard-listeners-http-bind"
          protocol: TCP
          port: 18083
          targetPort: 18083
        - name: "websocket"
          protocol: TCP
          port: 8080
          targetPort: 8080
  listenersServiceTemplate:
    metadata:
      name: emqx-listeners
    spec:
      type: ClusterIP
      ports:
        - name: "tcp-default"
          protocol: TCP
          port: 1883
          targetPort: 1883
```
Core log

```
EMQX_API_KEY__BOOTSTRAP_FILE [api_key.bootstrap_file]: /opt/emqx/data/bootstrap_api_key
EMQX_DASHBOARD__LISTENERS__HTTP__BIND [dashboard.listeners.http.bind]: 18083
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_CLUSTER__DNS__RECORD_TYPE [cluster.dns.record_type]: srv
EMQX_CLUSTER__DNS__NAME [cluster.dns.name]: emqx-headless.emqx.svc.cluster.local
EMQX_CLUSTER__DISCOVERY_STRATEGY [cluster.discovery_strategy]: dns
EMQX_NODE__ROLE [node.role]: core
EMQX_NODE__DATA_DIR [node.data_dir]: data
EMQX_NODE__COOKIE [node.cookie]: ******
EMQX_NODE__NAME [node.name]: emqx@emqx-core-6d6c7bcb6b-0.emqx-headless.emqx.svc.cluster.local
2023-09-06T10:17:42.756655+00:00 [warning] mria_mnesia: still waiting for table(s): ['$mria_rlog_sync']
2023-09-06T10:17:42.757090+00:00 [warning] Check down_nodes should get [] but got ['emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local']
2023-09-06T10:18:12.791044+00:00 [warning] mria_mnesia: still waiting for table(s): ['$mria_rlog_sync']
2023-09-06T10:18:12.793961+00:00 [warning] Check down_nodes should get [] but got ['emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local']
2023-09-06T10:18:42.829306+00:00 [warning] mria_mnesia: still waiting for table(s): ['$mria_rlog_sync']
2023-09-06T10:18:42.829980+00:00 [warning] Check down_nodes should get [] but got ['emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local']
2023-09-06T10:19:12.868038+00:00 [warning] mria_mnesia: still waiting for table(s): ['$mria_rlog_sync']
2023-09-06T10:19:12.868538+00:00 [warning] Check down_nodes should get [] but got ['emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local']
2023-09-06T10:19:18.850851+00:00 [warning] msg: Stopping mria, mfa: mria:stop/1, line: 134, reason: leave
2023-09-06T10:19:18.855232+00:00 [error] Supervisor: {local,mria_sup}. Context: start_error. Reason: mnesia_stopped. Offender: id=mria_schema,pid=undefined.
2023-09-06T10:19:18.863396+00:00 [error] crasher: initial call: application_master:init/4, pid: <0.2167.0>, registered_name: [], exit: {{{shutdown,{failed_to_start_child,mria_schema,mnesia_stopped}},{mria_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, ancestors: [<0.2166.0>], message_queue_len: 1, messages: [{'EXIT',<0.2168.0>,normal}], links: [<0.2166.0>,<0.1988.0>], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 28, reductions: 172; neighbours:
2023-09-06T10:19:18.880047+00:00 [error] crasher: initial call: application_master:init/4, pid: <0.2164.0>, registered_name: [], exit: {{bad_return,{{emqx_machine_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{mria,{{shutdown,{failed_to_start_child,mria_schema,mnesia_stopped}},{mria_app,start,[normal,[]]}}}}},[{mria,start,0,[{file,"mria.erl"},{line,125}]},{ekka,start,0,[{file,"ekka.erl"},{line,94}]},{emqx_machine,start,0,[{file,"emqx_machine.erl"},{line,45}]},{emqx_machine_app,start,2,[{file,"emqx_machine_app.erl"},{line,27}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, ancestors: [<0.2163.0>], message_queue_len: 1, messages: [{'EXIT',<0.2165.0>,normal}], links: [<0.2163.0>,<0.1988.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 28, reductions: 195; neighbours:
{removed_failing_handler,console}
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx_machine,{bad_return,{{emqx_machine_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{mria,{{shutdown,{failed_to_start_child,mria_schema,mnesia_stopped}},{mria_app,start,[normal,[]]}}}}},[{mria,start,0,[{file,\"mria.erl\"},{line,125}]},{ekka,start,0,[{file,\"ekka.erl\"},{line,94}]},{emqx_machine,start,0,[{file,\"emqx_machine.erl\"},{line,45}]},{emqx_machine_app,start,2,[{file,\"emqx_machine_app.erl\"},{line,27}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
Logger - error: Kernel pid terminated (application_controller) ({application_start_failure,emqx_machine,{bad_return,{{emqx_machine_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{mria,{{shutdown,{failed_to_start_child,mria_schema,mnesia_stopped}},{mria_app,start,[normal,[]]}}}}},[{mria,start,0,[{file,"mria.erl"},{line,125}]},{ekka,start,0,[{file,"ekka.erl"},{line,94}]},{emqx_machine,start,0,[{file,"emqx_machine.erl"},{line,45}]},{emqx_machine_app,start,2,[{file,"emqx_machine_app.erl"},{line,27}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}})
Crash dump is being written to: /opt/emqx/log/erl_crash.dump...done
```

**Comment by Rory-Z** [comment]
Hi, @webfrank I'm try it in Minikube via your YAML file, and looks good.

Check your emqx's log, I guess maybe some network issue.

@ieQu1 @id Any ideas ?

**Comment by webfrank** [comment]
Could it be the old k8s version? I'm still on 1.21

**Comment by Rory-Z** [comment]
> Could it be the old k8s version? I'm still on 1.21

Sorry, the 1.21 is too old, I'm create a Kubernetes 1.21.9 via Minikube, and install cert-manager is failed, I'm try the cert-mangaer version of 1.12 / 1.11 / 1.10, it's still failed.

**Comment by webfrank** [comment]
I tested with 1.0.4. The reason is that i need to upgrade a production
cluster which is still on 1.21

Il giorno gio 7 set 2023 alle 11:35 Rory ***@***.***> ha
scritto:

**Comment by Rory-Z** [comment]
> I tested with 1.0.4. The reason is that i need to upgrade a production
cluster which is still on 1.21
 
Is your means the cert-manger 1.0.4 ?

**Comment by webfrank** [comment]
Yes, to install everything on k8s 1.21 I installed cert-manager 1.0.4

Il giorno ven 8 set 2023 alle 04:12 Rory ***@***.***> ha
scritto:

**Comment by Rory-Z** [comment]
Is it work ? I try install cert-manger 1.0.4 like this:
```
$ helm upgrade --install cert-manager jetstack/cert-manager   --namespace cert-manager   --create-namespace   --set installCRDs=true --version=v1.0.4
```
and looks good, but when I install emqx operator, I got error:
```
$ helm upgrade --install emqx-operator emqx/emqx-operator   --namespace emqx-operator-system   --create-namespace --version=2.2.2

Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
```

But it doesn't matter, I still think you may have encountered some network problems. Some of our clients also deployed EMQX on 1.21 and it worked for them.

@ieQu1 @id Could you please take a look of the emqx's log ?

**Comment by Rory-Z** [comment]
Hi @webfrank I see the log have this context:
```
2023-09-06T10:17:42.757090+00:00 [warning] Check down_nodes should get [] but got ['emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local']
```

It has both emqx-core-7f595998b4 and emqx-core-6d6c7bcb6b, so I think your EMQX is not a clean environment. Can you describe what you have done?

**Comment by zmstone** [comment]
We have received similar reports on 5.1.x.
The solution is still being investigated.

**Comment by webfrank** [comment]
I started from scratch on minikube installing 1.21. 

Installed cert manager 1.0.4, the only one I found working. 

Tried 5.1.6 and after 5.1.5 with those errors.

**Comment by Rory-Z** [comment]
Hi @webfrank This is a EMQX issue, so let's wait EMQX fix it.
For now, could you please delete `lifecycle` in EMQX customer resource and retry it, I think it will be batter

**Comment by webfrank** [comment]
Hi, I tried several scenarios but leaving out lifecycle when I try to update I stuck on aria waiting for a stopped node to come up because the old node didn't leave the cluster.

I suspect the issue comes from the persistent volume which retains some old config.

**Comment by zmstone** [comment]
Hi Again.

We had quite some discussions internally, collectively, we tried to find patterns in similar reported issues.
There are below different scenarios which may lead to the logging of `down_nodes` in a loop.

1. Deleted node(s) is still in the cluster.
  To permanently delete a node from the cluster, it should leave the cluster first.
  This is more commonly to be observed in k8s if the nodes get assigned with random names and deleted permanently from k8s after all  pods are down.
2. A true 'split-brain' situation. This is a known issue, which can happen in case of power-off, or pull-cable situations.
  To recover, one would need to run `emqx_cluster_rescue` script to repair the schema
3. Node connectivity issues.
  The nodes would report up and listening to ports (and maybe even the ports are reachable),
  however, (all, or some of) the nodes cannot communicate with each other.
  In one example case, we found in a 3 node cluster, A, B, C, the nodes were not running in a full mech network, everything is running fine, except that A,B cannot get replies from C.
4. In k8s, for a size N cluster, if the scaling factor is set to less than N, then there is a chance for the first nodes to be booted waits for the ones in the next batch.

We believe it's 1st case according to the logs reported in this thread.
Static node names should be used for EMQX core-nodes.
e.g. `emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local` -> `emqx@emqx-core-1.emqx-headless.emqx.svc.cluster.local`

**Comment by Rory-Z** [comment]
> Static node names should be used for EMQX core-nodes.

Hi @zmstone 

Operator now uses dynamic names for muilt version clusters. It will create Pods named `emqx-core-$hash-$index` like `emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local`, where $hash is calculated based on the Pod template. Therefore, when users update the pod template (such as updating the pod image), new Pods will be generated, like `emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local `.

When a new Pod joins the cluster and becomes ready, the Operator will gradually delete the old Pods.

What could be the problem with this? I think it should work.

**Comment by webfrank** [comment]
Hi, from what I’ve observed case is n.1. The issue is for sure related to
old k8s 1.21. I’ve tested on 1.23 starting from 5.1.3 and upgrading to
5.1.6 without issue. I’ll test the full upgrade path from 5.0.14 and
operator 2.1.4 to the lastest and I’ll post here the results.

Il giorno mar 12 set 2023 alle 03:59 Rory ***@***.***> ha
scritto:

**Comment by Rory-Z** [comment]
Hi, @webfrank Maybe this is helpful for you: https://github.com/emqx/emqx-operator/issues/932#issuecomment-1695137452

**Comment by webfrank** [comment]
Thank you @Rory-Z , this is exactly what I'm following for the upgrade path.

**Comment by zmstone** [comment]
The preStop command is `command: ["/bin/sh","-c","emqx ctl cluster leave"]`.
We need to understand why this leave command did not work (e.g. before `6d6c7bcb6b-0` restarted).
And if `6d6c7bcb6b-0` left the cluster before, and it comes back using the same node name, it should not re-use the old `data/mnesia` dir.

**Comment by ondrej-smola** [comment]
Same issue here ... can easily reproduce on 2.2.2 with emqx 5.3.0 ... in my case install using 2 replicas -> change EMQX object to trigger rolling update, after update delete both pods (e.g. using kubectl) and cluster wont start afterwards

![image](https://github.com/emqx/emqx-operator/assets/851390/ad3edc30-8917-4413-af83-bb22cf92eeb9)
![image](https://github.com/emqx/emqx-operator/assets/851390/8b9cb99e-cde8-49f8-a155-a94406c47f16)

**Comment by ondrej-smola** [comment]
From what I see previous containers are also visible from GUI
![image](https://github.com/emqx/emqx-operator/assets/851390/69ffb3ca-ffdf-404f-b1a9-76299be7ebbd)

**Comment by ondrej-smola** [comment]
@zmstone I dont think relying on preStop is good strategy in Kubernetes as there are no guarantees that it will be called consistently in multiple fail case scenarios

**Comment by ondrej-smola** [comment]
its groving ad infinite it seems ...
![image](https://github.com/emqx/emqx-operator/assets/851390/a37c4492-21f0-4b69-81dd-b61458cf8881)

**Comment by ondrej-smola** [comment]
Force killing pods in above state just trigger infinite restart as described above. This basically renders operator unusable for us :( . Last scenarion tested on 5.1.3 ...

**Comment by ondrej-smola** [comment]
Only recovery solution I found is deleting PVC and deleting pods - forcing "clean start"

**Comment by ondrej-smola** [comment]
Not trying to reproduce without persistence and unable to do so. "Grey"/unavailable nodes are still present in GUI but after both pod restart they disappear and cluster starts ok.

**Comment by Rory-Z** [comment]
Hi @ondrej-smola sorry for delay,  It looks a bit chaotic. could you describe step by step how you operated ? This issue has the historical information of others. Perhaps creating a new issue would be a good idea.

**Comment by ondrej-smola** [comment]
@Rory-Z sorry for confusion ... will try to formulate it better in separate issue. My goal was to trying to illustrate what actually is causing same issue but caused by updating cluster spec. I think this issue is related to previous instances staying in "membership" that should not be there.

**Comment by ondrej-smola** [comment]
It can be clearly seen in line 
`2023-09-06T10:18:42.829980+00:00 [warning] Check down_nodes should get [] but got ['emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@emqx-core-6d6c7bcb6b-1.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-0.emqx-headless.emqx.svc.cluster.local', 'emqx@emqx-core-7f595998b4-1.emqx-headless.emqx.svc.cluster.local']` from original issue description that there multiple pods from different statefulset (7f595998b4,  6d6c7bcb6b) causing this

**Comment by Rory-Z** [comment]
OK, let me think

+ First you deploy the EMQX cluster, and EMQX Operator create a statefulSet version

+ Second you change something for EMQX customer resource, and EMQX Operator create a new statefulSet version

+ And then the EMQX pod report warning log, the EMQX customer resource did not ready, it maybe have `Available` in status condition

If what I said is correct, I would like to confirm the following questions.

+ Did you set any `lifecycle.preStop` in EMQX customer resource ?

+ Did you delete old version pod by yourself, not EMQX operator delete it  ?

**Comment by ondrej-smola** [comment]
@Rory-Z after just change to statefulset it adds new ready emqx nodes and previous version emqx nodes are reported as unavailable. When i force restart all active emqx nodes they wont boot up and will end up in crashbacloop with logs similar what this issue is about.

**Comment by Rory-Z** [comment]
> When i force restart all active emqx nodes (current statefulset version) they wont boot up and will end up in crashbacloop with logs similar what this issue is about.

Before you restart active emqx pod, what is their condition? ? And how do you restart the node, rollout restart or delete all of pod ?

**Comment by Rory-Z** [comment]
I have a conjecture, when create a new statefulSet and delete the old statefulSet, there is a window period during which emqx considers that both versions of the emqx pod are in the cluster, and EMQX operator will scale down the old version of emqx pod one by one, if restart the new version of emqx pod at this time, maybe the new version of emqx pod didn't know the old version of emqx pod has been deleted, so they will wait the old version of emqx pod.

Just I guess, @zmstone any ideas ?

**Comment by ondrej-smola** [comment]
Yes, the other problem is that in my case the "windows period" seems to be "infinite" (hours at least) as ilustrated by my screenshot https://github.com/emqx/emqx-operator/issues/942#issuecomment-1745511908

**Comment by Rory-Z** [comment]
> Yes, the other problem is that in my case the "windows period" seems to be "infinite" (hours at least) as ilustrated by my screenshot [#942 (comment)](https://github.com/emqx/emqx-operator/issues/942#issuecomment-1745511908)

No, I think it is other issue, if it keeps appearing, could you open the debug log of EMQX Operator and share the log? You can set `development = true` in the helm chart to open the debug log.
