### ISSUE TITLE
v2beta1 EMQXReplicantTemplateSpec."toleRations" should be "tolerations" by Kubernetes conventions

### ISSUE THREAD

**Issue by ondrej-smola** [emqx/emqx-operator#944]
It is not just in typo in docs but it actually ignored by operator if written as "tolerations" in EMQX object spec. Very confusing for any Kubernetes user.

**Comment by Rory-Z** [comment]
Yes, you are right. Should we fix it in the next patch version?  I'm worried that it will cause inconvenience to the users who are currently using it.

**Comment by ondrej-smola** [comment]
Agree on next patch - it can break current deployments

**Comment by ondrej-smola** [comment]
Also needs to be fixed in EMQXCoreTemplateSpec

**Comment by Rory-Z** [comment]
OK, let's do it.

**Comment by Rory-Z** [comment]
> It is not just in typo in docs but it actually ignored by operator if written as "tolerations" in EMQX object spec. Very confusing for any Kubernetes user.

Hi, @ondrej-smola In my case, the EMQX Operator will not ignore `tolerations`, I got this error: `Error from server (BadRequest): error when creating "config/samples/emqx/v2beta1/emqx-slim.yaml": EMQX in version "v2beta1" cannot be handled as a EMQX: strict decoding error: unknown field "spec.coreTemplate.spec.tolerations"`

So I compatible the `tolerations` and `toleRations`, what do you think

**Comment by ondrej-smola** [comment]
I deployed it using GitOps (ArgoCD) and it just drops the "tolerations" part 

![image](https://github.com/emqx/emqx-operator/assets/851390/98f08917-6685-4920-9d37-0aeebfff9266)

**Comment by Rory-Z** [comment]
Hi @ondrej-smola , the EMQX Operator 2.2.3 has been released, you can try it.
I will close this issue, if you have any question, you can reopen it in anytime.
