### ISSUE TITLE
Allow for service annotations on listeners service

### ISSUE THREAD

**Issue by jasmdk** [emqx/emqx-operator#951]
**Is your feature request related to a problem? Please describe.**
In a setup with a LoadBalancer IP, we would like the option of reserving an IP in Azure and ensure that the service picks up the reserved IP rather than requesting an arbitrary IP.

**Describe the solution you'd like**
Allow the EMQX CRD to set serviceAnnotations for the listener service so that an annotation like "service.beta.kubernetes.io/azure-load-balancer-resource-group" can be used to specify the resource group for a static ip,

**Describe alternatives you've considered**
The alternative is to place the public ip in the generated resource group or accept that Azure will reserve one for you that only lives as long as the service do not get deleted.

**Additional context**
[Azure static ip](https://learn.microsoft.com/en-us/azure/aks/static-ip)

**Comment by Rory-Z** [comment]
Hi, @jasmdk you can set service annotations in `.spec.listenersServiceTempalte.metadata.annotations`
