### ISSUE TITLE
secret not found

### ISSUE THREAD

**Issue by seaurching** [emqx/emqx-operator#956]
**Describe the bug**
The emqx-operator-controller could not startup with secret not found. 
```
  ----     ------       ----                  ----               -------
  Normal   Scheduled    4m23s                 default-scheduler  Successfully assigned emqx-operator-system/emqx-operator-controller-manager-756d559db5-vl45l to 10.20.0.251
  Warning  FailedMount  13s (x10 over 4m23s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "emqx-operator-webhook-server-cert" not found
  Warning  FailedMount  5s (x2 over 2m20s)    kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert emqx-operator-token-k44hk]: timed out waiting for the condition
```
**To Reproduce**
1. Install cert-manager
2. Helm install operator
```
kubectl apply -f https://ghproxy.com/https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml
helm install--install emqx-operator ./emqx-operator-2.2.3.tgz   --namespace emqx-operator-system   --create-namespace
```
**Expected behavior**
```
# kubectl get pod -n emqx-operator-system
NAME                                                READY   STATUS    RESTARTS        AGE
emqx-operator-controller-manager-686c8484c6-8dwmq   1/1     Running   8 (5m45s ago)   30h
[root@apiserver:/root]
# kubectl get secrets -n emqx-operator-system
NAME                                  TYPE                 DATA   AGE
emqx-operator-webhook-server-cert     kubernetes.io/tls    3      30h
sh.helm.release.v1.emqx-operator.v1   helm.sh/release.v1   1      30h
```

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: v1.21.3
- Cloud-provider/provisioner:
- emqx-operator version: 2.2.3

**Comment by Rory-Z** [comment]
Hi @seaurching I think the reason because the cert-manager is not ready, could you please wait the cert-manager is ready, and retry it. you can running this: `kubectl wait --for=condition=Ready pods -l "app.kubernetes.io/instance=cert-manager" -n cert-manager`

**Comment by seaurching** [comment]
> Hi @seaurching I think the reason because the cert-manager is not ready, could you please wait the cert-manager is ready, and retry it. you can running this: `kubectl wait --for=condition=Ready pods -l "app.kubernetes.io/instance=cert-manager" -n cert-manager`

```
Unsupported Media Type" key="emqx-operator-system/emqx-operator-serving-certE0928 06:37:42.846310       1 controller.go:167] "cert-manager/certificates-issuing: re-queuing item due to error processing" err="failed to apply secret emqx-operator-system/emqx-operator-webhook-server-cert: 415: Unsupported Media Type" key="emqx-operator-system/emqx-operator-serving-cert"
E0928 06:38:12.858525       1 controller.go:167] "cert-manager/certificates-issuing: re-queuing item due to error processing" err="failed to apply secret emqx-operator-system/emqx-operator-webhook-server-cert: 415: Unsupported Media Type" key="emqx-operator-system/emqx-operator-serving-cert"
E0928 06:38:42.869713       1 controller.go:167] "cert-manager/certificates-issuing: re-queuing item due to error processing" err="failed to apply secret emqx-operator-system/emqx-operator-webhook-server-cert: 415: Unsupported Media Type" key="emqx-operator-system/emqx-operator-serving-cert"
```

**Comment by Rory-Z** [comment]
Hi @seaurching could you please try the cert-manger v1.12.4, that is good for me, I will check why it not work for v1.13

**Comment by Rory-Z** [comment]
Hi @seaurching In our [CI workflow](https://github.com/emqx/emqx-operator/actions/runs/6437644397/job/17483136370#step:6:28), the cert-manger 1.13.1 is work. so I will close this issue, if you have question, you can reopen it in anytime

**Comment by seaurching** [comment]
@Rory-Z It's not worked for emqx-operator to create secret on cert-manager-1.13.1
![image](https://github.com/emqx/emqx-operator/assets/7349963/db4de702-03f5-45b5-86eb-90ea7bf58531)

**Comment by seaurching** [comment]
> Hi @seaurching In our [CI workflow](https://github.com/emqx/emqx-operator/actions/runs/6437644397/job/17483136370#step:6:28), the cert-manger 1.13.1 is work. so I will close this issue, if you have question, you can reopen it in anytime

I cannot reopen this issue

**Comment by Rory-Z** [comment]
I reopen it. I think this issue because the cert-manger didn't create the secret of the `emqx-operator-webhook-server-cert`
I see your Kubernetes version is 1.21, and cert-manger 1.13 didn't support it, check https://cert-manager.io/docs/releases/#supported-releases
Maybe you can delete cert-manager and emqx operator, and selector some old cert-manager version, and reinstall cert-manager and emqx operator.
