### ISSUE TITLE
Operator updates pod condition status on old pod

### ISSUE THREAD

**Issue by SkouRene** [emqx/emqx-operator#961]
**Describe the bug**
When deleting a emqx cluster node ( pod ) the emqx operator fails to update the new cluster core node ( pod ) with pod readiness gate condition. Instead it calls the old cluster core node (pod) which make the new cluster core node ( pod ) unreachable until we delete all resources and start over.

**To Reproduce**
In a running emqx, delete one of the core nodes.

**Expected behavior**
The operator should call the new cluster core node to update the pod readiness gate to get the cluster core node in ready state

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: 1.25.6
- Cloud-provider/provisioner: Azure
- emqx-operator version: 5.3.0
- Install method: e.g. helm/static manifests helm

**Comment by Rory-Z** [comment]
Hi @SkouRene In your describe, looks have the new cluster and the old cluster, so the EMQX customer resource is in the blue-green upgrade progress ?
And when you delete the pod of the old cluster, what is the condtions of the EMQX customer resource status ?

**Comment by SkouRene** [comment]
The status is ReplicantNodesProgressing

**Comment by Rory-Z** [comment]
> The status is ReplicantNodesProgressing

Seems you enable replicant nodes of EMQX ? could you please share your YAML file ?

**Comment by jasmdk** [comment]
Is it possible to re-open this issue if I can add more details on how to reproduce the issue?

**Comment by Rory-Z** [comment]
Hi @jasmdk could you please share your YAML file ? maybe you can create a new issue

**Comment by jasmdk** [comment]
> Hi @jasmdk could you please share your YAML file ? maybe you can create a new issue

Hi @Rory-Z , I can create a new issue, but my conclusions so far is that this only happens if I have a single core node and no replicants at all. I am not sure if it is expected to always have at least one replica. If zero replicants is a valid setup, then the issue is relevant.

**Comment by Rory-Z** [comment]
Hi @jasmdk Is your EMQX operator version is 2.2.4 ? If yes, please shell your EMQX yaml file, it will helper for me.
