### ISSUE TITLE
Migrating from v2alpha to V2beta

### ISSUE THREAD

**Issue by fabltd** [emqx/emqx-operator#976]
Hi 

When migrating from the alfa to beta apiversion it appeats theat the bootstrap config is longer supported.

If this is the case how is the default dashboard username / password set?

Thanks

**Comment by Rory-Z** [comment]
OK, I get you.
You can use `.spec.config.data` in `v2beta1`. Because in `v2beta1`, the EMQX operator can manager the configure of EMQX.

**Comment by rabbitlhf** [comment]
> OK, I get you. You can use `.spec.config.data` in `v2beta1`. Because in `v2beta1`, the EMQX operator can manager the configure of EMQX.

is there any examples about  `.spec.config.data` in `v2beta1`

**Comment by Rory-Z** [comment]
@rabbitlhf You can check here: https://github.com/emqx/emqx-operator/blob/fa4d0b0ed0e614c2face4214d6178ab3ff6042e0/config/samples/emqx/v2beta1/emqx-full.yaml#L13
