### ISSUE TITLE
Make revisionHistoryLimit available for the operator deployment in the chart

### ISSUE THREAD

**Issue by rouke-broersma** [emqx/emqx-operator#999]
**Is your feature request related to a problem? Please describe.**
EMQX resource exposes the revisionHistoryLimit in the spec, I would like to set the revision history limit for the operator as well.

**Describe the solution you'd like**
Make the revisionHistoryLimit available in the helm chart

**Additional context**
I don't use revisions so I want to set it to 0.

**Comment by Rory-Z** [comment]
Sure, let's do it.

**Comment by Rory-Z** [comment]
Done this issue in this PR: https://github.com/emqx/emqx-operator/pull/1001
